#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Train WAE model 01 using prebuilt cached datasets (pickled NumPy arrays).
Overview
--------
This script is a sibling of `encoder/train_WAE_01.py` but, instead of
streaming random rows from many raw files via `EfficientDataLoader`, it
trains from two prebuilt, non-IO-bound datasets generated by
`build_autoencoder_dataset.py`:

- training_auto_encoder.pkl
- validation_auto_encoder.pkl

These files are expected to live under the directory pointed to by
`experiment.preferences -> root_path` (or a user-specified directory).
Each file contains a single NumPy array with shape:

    (num_rows, feature_dim)

Using these dense, contiguous arrays eliminates the file fan-out and
random-access overhead, enabling much faster training iterations.

Weights & Biases (wandb)
------------------------
We continue to log both per-epoch and optional per-step metrics to wandb.
On Windows, symlink creation is disabled for `wandb.save()` to avoid
WinError 1314; a best-effort file copy fallback is provided.

Usage examples
--------------
    # Default paths as specified in experiment.preferences
    python -m encoder.train_WAE_01_cached

    # Explicit filenames and batch size
    python -m encoder.train_WAE_01_cached \
        --train_file training_auto_encoder.pkl \
        --val_file   validation_auto_encoder.pkl \
        --batch_size 256

    # Resume from a checkpoint
    python -m encoder.train_WAE_01_cached --resume_checkpoint encoder/saved_models/WAE_Cached_001_final.pt

Notes
-----
- For very large cached arrays, ensure sufficient system RAM. You can
  use `--train_limit` / `--val_limit` to cap rows for quick experiments.
- The model architecture and loss are sourced from `encoder/model_WAE_01.py`.
"""

import os
import sys
import time
import logging
import argparse
import pickle
import re
import glob
import shutil
from typing import Optional, Tuple

import numpy as np
import torch
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from torch.utils.tensorboard import SummaryWriter

# Resolve project directories so we can import local modules
PARENT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PARENT_DIR not in sys.path:
    sys.path.append(PARENT_DIR)

from encoder.model_WAE_01 import WAE  # noqa: E402
from Ordered_001_Initialize import HostPreferences  # noqa: E402

# ----------------------
# Default training config
# ----------------------
MODEL_NAME = "WAE_Cached_006_Corrected"
DEFAULT_BATCH_SIZE = 128
DEFAULT_EPOCHS = 2500
DEFAULT_LR = 1e-6
SAVE_INTERVAL = 2  # save every N epochs
CHECKPOINTS_TO_KEEP = 5  # keep last K rolling checkpoints

# ----------
# Logging
# ----------
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# ================
# Accelerator utils
# ================
CSI = "\033["
RESET = f"{CSI}0m"
COLORS = [31, 33, 32, 36, 34, 35]  # R, Y, G, C, B, M
GREEN = f"{CSI}32m"
RED = f"{CSI}31m"
GREY = f"{CSI}90m"


def _rainbow(msg: str) -> str:
    out = []
    k = 0
    for ch in msg:
        if ch.strip():
            out.append(f"{CSI}{COLORS[k % len(COLORS)]}m{ch}{RESET}")
            k += 1
        else:
            out.append(ch)
    return ''.join(out)


def _fmt_delta(curr: float, prev: float | None, *, lower_is_better: bool = True, suffix: str = "") -> str:
    """Return a colored delta string like ' (-0.0012)' with green for improvement and red for regression.
    If prev is None, return empty string.
    """
    try:
        if prev is None:
            return ""
        diff = curr - prev
        sign = "+" if diff > 0 else ("-" if diff < 0 else "±")
        color = GREEN if ((diff < 0) == lower_is_better) else (RED if diff != 0 else GREY)
        return f" ({color}{sign}{abs(diff):.6f}{suffix}{RESET})"
    except Exception:
        return ""


def accelerator_report() -> Tuple[torch.device, dict]:
    """Detect CUDA/MPS/CPU, print a colorful diagnostic, and return (device, info)."""
    pyv = torch.__version__
    try:
        import platform
        py = platform.python_version()
    except Exception:
        py = "?"

    has_cuda = torch.cuda.is_available()
    cuda_version = getattr(torch.version, 'cuda', None)
    mps_built = hasattr(torch.backends, 'mps') and torch.backends.mps.is_built()
    mps_avail = mps_built and torch.backends.mps.is_available()

    device = torch.device('cuda') if has_cuda else (torch.device('mps') if mps_avail else torch.device('cpu'))

    lines = [
        f"Python: {py} | PyTorch: {pyv}",
        f"CUDA available: {has_cuda} | CUDA toolkit: {cuda_version}",
        f"MPS built: {mps_built} | MPS available (runtime): {mps_avail}",
        f"Selected default device: {device}",
    ]

    if has_cuda:
        try:
            idx = torch.cuda.current_device()
            props = torch.cuda.get_device_properties(idx)
            cap = torch.cuda.get_device_capability(idx)
            lines += [
                f"CUDA device count: {torch.cuda.device_count()}",
                f"Current device: {idx} | Name: {props.name}",
                f"Compute capability: {cap[0]}.{cap[1]} | Total memory: {props.total_memory/1024**3:.2f} GiB",
            ]
        except Exception as e:
            lines.append(f"CUDA detail query failed: {e}")

    for ln in lines:
        print(_rainbow(ln))
        logger.info(ln)

    return device, {
        'python': py,
        'torch': pyv,
        'cuda_available': has_cuda,
        'cuda_version': cuda_version,
        'mps_built': mps_built,
        'mps_available': mps_avail,
        'selected_device': str(device),
    }


# ---------
# wandb
# ---------
import wandb  # noqa: E402


def _parse_epoch_from_filename(filename: str, model_name: str) -> Optional[int]:
    """Extract epoch number from a checkpoint filename of the form
    f"{model_name}_epoch_<N>.pt". Returns None if no match.
    """
    try:
        base = os.path.basename(filename)
        m = re.match(rf"{re.escape(model_name)}_epoch_(\d+)\.pt$", base)
        if m:
            return int(m.group(1))
    except Exception:
        pass
    return None


essential_ckpt_patterns = (
    # anything named *_final.pt should never be pruned
    "_final.pt",
)


def prune_checkpoints(dir_path: str, model_name: str, keep: int) -> None:
    """Keep only the newest `keep` epoch checkpoints in `dir_path` for `model_name`.

    - Matches files like f"{model_name}_epoch_*.pt"
    - Excludes any file that ends with "_final.pt"
    - Deletes oldest files first, keeping at most `keep` newest.
    - Best-effort; logs and continues on errors.
    """
    try:
        pattern = os.path.join(dir_path, f"{model_name}_epoch_*.pt")
        files = glob.glob(pattern)
        if not files:
            return
        # Exclude any accidental finals
        files = [f for f in files if not f.endswith("_final.pt")]
        # Build list of (epoch, path)
        items = []
        for fpath in files:
            ep = _parse_epoch_from_filename(fpath, model_name)
            if ep is not None:
                items.append((ep, fpath))
        if not items:
            return
        items.sort(key=lambda x: x[0])  # ascending by epoch
        # Determine which to delete
        to_delete = items[:-keep] if keep > 0 else items
        for ep, fpath in to_delete:
            try:
                os.remove(fpath)
                logger.info(f"Pruned old checkpoint (epoch {ep}): {fpath}")
            except Exception as e:
                logger.warning(f"Failed to remove old checkpoint {fpath}: {e}")
    except Exception as e:
        logger.warning(f"prune_checkpoints failed for {dir_path}: {e}")


def prune_wandb_checkpoints_if_present(model_name: str, keep: int) -> None:
    """Prune checkpoint copies inside the current W&B run directory (Windows copy fallback).

    We mirror the location used in the fallback copy: wandb.run.dir/files/saved_models
    """
    try:
        run = getattr(wandb, 'run', None)
        if not run:
            return
        run_dir = getattr(run, 'dir', None)
        if not run_dir:
            return
        dst_dir = os.path.join(run_dir, 'files', 'saved_models')
        if os.path.isdir(dst_dir):
            prune_checkpoints(dst_dir, model_name, keep)
    except Exception as e:
        logger.warning(f"prune_wandb_checkpoints_if_present failed: {e}")


def _load_preferences(path: Optional[str]) -> HostPreferences:
    """Load HostPreferences from an explicit path or from project root by default."""
    if path is None:
        preferences_path = os.path.join(PARENT_DIR, "experiment.preferences")
    else:
        preferences_path = path
    prefs = HostPreferences(filename=preferences_path)
    # Adopt logging level if provided
    lvl = getattr(logging, getattr(prefs, 'logging_level', 'INFO').upper(), None)
    if isinstance(lvl, int):
        logger.setLevel(lvl)
        logger.info(f"Set logging level to {getattr(prefs, 'logging_level', 'INFO').upper()}")
    return prefs


def _load_cached_array(file_path: str, limit: Optional[int] = None) -> np.ndarray:
    """Load a pickled NumPy array from `file_path` and optionally cap rows.

    Ensures dtype float32 for compact storage and faster training.
    """
    t0 = time.time()
    with open(file_path, 'rb') as f:
        arr = pickle.load(f)
    if not isinstance(arr, np.ndarray):
        raise TypeError(f"Cached file {file_path} does not contain a NumPy array; got {type(arr)}")
    if arr.dtype != np.float32:
        arr = arr.astype(np.float32, copy=False)
    if limit is not None:
        arr = arr[:int(limit)]
    t1 = time.time()
    logger.info(f"Loaded cached array: {file_path} shape={arr.shape} dtype={arr.dtype} in {t1 - t0:.2f}s")
    return arr


def _make_loader(
        arr: np.ndarray,
        batch_size: int,
        shuffle: bool,
        num_workers: int = 0,
        prefetch_factor: int = 2,
        persistent_workers: bool = False,
        pin_memory: bool = True,
    ) -> DataLoader:
    """Wrap a NumPy array into a TensorDataset/DataLoader.

    - Uses pinned memory tensors on CUDA for faster H2D transfers.
    - Drop last is False to keep as many samples as possible per epoch.
    - Supports multi-worker prefetch to keep the GPU fed.
    """
    # Create a torch tensor view (copies once from NumPy into a single big tensor)
    x_tensor = torch.from_numpy(arr)  # float32 ensured earlier
    dataset = TensorDataset(x_tensor)

    # persistent_workers is only valid when num_workers > 0
    use_persistent = bool(persistent_workers and num_workers > 0)

    # On CPU-only runs, pin_memory has no effect; on CUDA it accelerates H2D
    loader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        pin_memory=pin_memory,
        drop_last=False,
        num_workers=max(0, int(num_workers)),
        prefetch_factor=int(prefetch_factor) if int(num_workers) > 0 else None,
        persistent_workers=use_persistent,
    )
    return loader


def main():
    parser = argparse.ArgumentParser(description="Train WAE model 01 using cached datasets (pickled arrays)")

    # Paths / files
    parser.add_argument('--preferences', type=str, default=None,
                        help='Path to experiment.preferences (defaults to project root).')
    parser.add_argument('--root', type=str, default=None,
                        help='Root directory that contains cached files; defaults to preferences.root_path')
    parser.add_argument('--train_file', type=str, default='training_auto_encoder.pkl',
                        help='Training cached filename (under --root).')
    parser.add_argument('--val_file', type=str, default='validation_auto_encoder.pkl',
                        help='Validation cached filename (under --root).')
    parser.add_argument('--test_file', type=str, default=None,
                        help='Optional test cached filename (under --root). If provided, evaluate RMSE after training.')

    # Training hyperparameters
    parser.add_argument('--batch_size', type=int, default=DEFAULT_BATCH_SIZE)
    parser.add_argument('--epochs', type=int, default=DEFAULT_EPOCHS)
    parser.add_argument('--learning_rate', type=float, default=DEFAULT_LR)
    parser.add_argument('--save_interval', type=int, default=SAVE_INTERVAL)

    # DataLoader performance controls (be careful with num_workers on Windows)
    parser.add_argument('--num_workers', type=int, default=0,
                        help='DataLoader workers. WARNING: On Windows with a large in-memory TensorDataset,\n'
                             'setting this >0 can duplicate the dataset in each worker and blow up RAM. Use with care.')
    parser.add_argument('--prefetch_factor', type=int, default=2,
                        help='Number of batches prefetched per worker when num_workers>0.')
    parser.add_argument('--persistent_workers', action='store_true',
                        help='Keep DataLoader workers alive between epochs (requires num_workers>0).')
    parser.add_argument('--no_pin_memory', action='store_true',
                        help='Disable pinned memory for host-to-device copies.')

    # Perf/instrumentation
    parser.add_argument('--profile_steps', type=int, default=0,
                        help='If >0, log per-step detailed timings for the first N steps of each epoch.')
    parser.add_argument('--sync_profile', action='store_true',
                        help='Force CUDA synchronize around profiled regions for accurate timings (slower).')
    parser.add_argument('--amp', action='store_true',
                        help='Enable torch.cuda.amp mixed precision for faster training on NVIDIA GPUs.')
    parser.add_argument('--compile', action='store_true',
                        help='Enable torch.compile to fuse/optimize model for PyTorch 2.x (may require warmup).')

    # Fast debug / limits
    parser.add_argument('--fast_debug', action='store_true', help='Use tiny settings for quick runs')
    parser.add_argument('--train_limit', type=int, default=None, help='Cap number of training rows (subset).')
    parser.add_argument('--val_limit', type=int, default=None, help='Cap number of validation rows (subset).')

    # Checkpointing / logging
    parser.add_argument('--resume_checkpoint', type=str, default=None,
                        help='Path to a checkpoint .pt file to resume from.')
    parser.add_argument('--no_wandb', action='store_true', help='Disable Weights & Biases logging')

    # Step logging verbosity
    parser.add_argument('--log_steps', action='store_true', help='Log per-step losses to TensorBoard (and W&B).')

    args = parser.parse_args()

    # Preferences and roots
    prefs = _load_preferences(args.preferences)
    root_dir = args.root or getattr(prefs, 'root_path', os.getcwd())

    # Resolve file paths
    train_path = os.path.join(root_dir, args.train_file)
    val_path = os.path.join(root_dir, args.val_file)

    if not os.path.isfile(train_path):
        raise FileNotFoundError(f"Training cached file not found: {train_path}")
    if not os.path.isfile(val_path):
        raise FileNotFoundError(f"Validation cached file not found: {val_path}")

    # Effective settings
    batch_size = int(args.batch_size)
    num_epochs = int(args.epochs)
    lr = float(args.learning_rate)
    save_every = max(1, int(args.save_interval))

    if args.fast_debug:
        # Keep memory/time small for quick iteration
        num_epochs = min(1, num_epochs)
        batch_size = min(128, batch_size)
        if args.train_limit is None:
            args.train_limit = 10_000
        if args.val_limit is None:
            args.val_limit = 10_000
        logger.info("FAST DEBUG active: epochs=%s, batch_size=%s, train_limit=%s, val_limit=%s",
                    num_epochs, batch_size, args.train_limit, args.val_limit)

    # -------- wandb: run init & notes --------
    wandb_run = None
    if not args.no_wandb:
        # Try to include the model source code as 'notes' to the run for convenience
        notes_content = ""
        model_filepath = os.path.join(PARENT_DIR, 'encoder', 'model_WAE_01.py')
        try:
            with open(model_filepath, 'r') as f:
                notes_content = f.read()
        except Exception as e:
            notes_content = f"Failed to load model file: {e}"

        # On Windows, disable symlinks to avoid WinError 1314 during wandb.save
        try:
            import platform
            is_windows = platform.system().lower().startswith('win')
        except Exception:
            is_windows = False

        wandb_run = wandb.init(
            project=MODEL_NAME,
            name=f"{MODEL_NAME}_run",
            notes=notes_content,
            config={
                'model': MODEL_NAME,
                'batch_size': batch_size,
                'epochs': num_epochs,
                'learning_rate': lr,
                'train_path': train_path,
                'val_path': val_path,
            },
            settings=wandb.Settings(symlink=not is_windows)
        )

    # Device setup & diagnostic
    device, acc_info = accelerator_report()
    try:
        if not args.no_wandb:
            wandb.config.update({'accelerator': acc_info}, allow_val_change=True)
    except Exception:
        pass

    # Output directories (relative to this script working directory)
    save_dir = os.path.join(PARENT_DIR, 'encoder', 'saved_models')
    log_dir = os.path.join(PARENT_DIR, 'encoder', 'logs')
    os.makedirs(save_dir, exist_ok=True)
    os.makedirs(log_dir, exist_ok=True)

    # TensorBoard writer
    writer = SummaryWriter(log_dir=log_dir)

    # ------------------
    # Data: load & wrap
    # ------------------
    train_np = _load_cached_array(train_path, limit=args.train_limit)
    val_np = _load_cached_array(val_path, limit=args.val_limit)

    train_loader = _make_loader(
        train_np,
        batch_size=batch_size,
        shuffle=True,
        num_workers=int(args.num_workers),
        prefetch_factor=int(args.prefetch_factor),
        persistent_workers=bool(args.persistent_workers),
        pin_memory=not args.no_pin_memory,
    )
    val_loader = _make_loader(
        val_np,
        batch_size=batch_size,
        shuffle=False,
        num_workers=int(args.num_workers),
        prefetch_factor=int(args.prefetch_factor),
        persistent_workers=bool(args.persistent_workers),
        pin_memory=not args.no_pin_memory,
    )

    # Free NumPy arrays early to reduce memory pressure; data now lives in tensors.
    del train_np
    del val_np

    # ---------------
    # Model & optim
    # ---------------
    model = WAE().to(device)

    # Optional compile for PyTorch 2.x
    if getattr(args, 'compile', False):
        try:
            model = torch.compile(model, mode='max-autotune')
            logger.info("Enabled torch.compile(max-autotune) for model")
        except Exception as e:
            logger.warning(f"torch.compile requested but failed: {e}")

    try:
        if device.type == 'cuda':
            torch.backends.cudnn.benchmark = True
    except Exception:
        pass
    # Prefer TensorFloat-32 / high-precision matmul for speed on Ampere+ GPUs when appropriate
    try:
        if device.type == 'cuda':
            torch.set_float32_matmul_precision('high')  # allowed: highest, high, medium
    except Exception:
        pass

    optimizer = optim.Adam(model.parameters(), lr=lr)

    # AMP mixed precision support
    use_amp = bool(args.amp and device.type == 'cuda')
    try:
        from torch.cuda.amp import GradScaler, autocast
    except Exception:
        GradScaler = None
        autocast = None
        use_amp = False
    scaler = GradScaler(enabled=use_amp) if GradScaler is not None else None

    start_epoch = 0

    # Optional: resume from checkpoint
    resume_path = args.resume_checkpoint
    if resume_path is None:
        # Convenience default: try the model's final checkpoint name in save_dir
        default_final = os.path.join(save_dir, f"{MODEL_NAME}_final.pt")
        if os.path.isfile(default_final):
            resume_path = default_final
    if resume_path and os.path.isfile(resume_path):
        try:
            logger.info(f"Loading checkpoint from {resume_path}")
            checkpoint = torch.load(resume_path, map_location=device)
            model.load_state_dict(checkpoint['model_state_dict'])
            if 'optimizer_state_dict' in checkpoint:
                optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
                # Move optimizer state to device
                for state in optimizer.state.values():
                    for k, v in state.items():
                        if isinstance(v, torch.Tensor):
                            state[k] = v.to(device)
            if 'scaler_state_dict' in checkpoint and scaler is not None:
                scaler.load_state_dict(checkpoint['scaler_state_dict'])
        except Exception as e:
            logger.error(f"Failed to load checkpoint: {e}")
            logger.error("Training will start from scratch.")
            
        # DIAGNOSTIC: Run a quick validation pass
        model.eval()
        with torch.no_grad():
            test_batch = next(iter(val_loader))[0].to(device)
            test_recon, test_z = model(test_batch)
            test_rmse = torch.sqrt(torch.mean((test_recon - test_batch) ** 2))
            logger.info(f"CHECKPOINT LOADED - Immediate validation RMSE: {test_rmse.item():.6f}")
        model.train()

    model.train()  # Add this explicitly
    logger.info(f"Initialized WAE model with latent dimension {model.fc4.out_features}")

    # =================
    # Training routine
    # =================
    global_step = 0
    train_start = time.time()
    prev_metrics = {}

    for epoch in range(start_epoch, num_epochs):
        model.train()
        epoch_loss = 0.0
        epoch_recon = 0.0
        epoch_mmd = 0.0
        epoch_triplet = 0.0
        num_batches = 0
        epoch_t0 = time.time()
        # Train SSE/MSE accumulators
        train_sse_sum = 0.0
        train_elem_sum = 0

        # Profiling controls
        profile_n = int(getattr(args, 'profile_steps', 0) or 0)
        sync_profile = bool(getattr(args, 'sync_profile', False)) and (device.type == 'cuda')
        step_idx = 0

        for batch in train_loader:
            step_wall_t0 = time.time()
            # batch is a tuple from TensorDataset
            x_cpu = batch[0]

            # Move to device; `pin_memory=True` at loader level enables non_blocking
            t_h2d0 = time.time()
            x = x_cpu.to(device, non_blocking=(device.type == 'cuda'))
            if sync_profile:
                torch.cuda.synchronize()
            t_h2d1 = time.time()

            # Forward
            t_fwd0 = time.time()
            if use_amp:
                with autocast():
                    recon_x, z = model(x)
                    loss, recon_loss, mmd_loss, triplet_loss = model.loss_function(recon_x, x, z)
            else:
                recon_x, z = model(x)
                loss, recon_loss, mmd_loss, triplet_loss = model.loss_function(recon_x, x, z)
            if sync_profile:
                torch.cuda.synchronize()
            t_fwd1 = time.time()

            # Backward + step
            t_bwd0 = time.time()
            optimizer.zero_grad(set_to_none=True)
            if use_amp and scaler is not None:
                scaler.scale(loss).backward()
                if sync_profile:
                    torch.cuda.synchronize()
                t_bwd1 = time.time()
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                if sync_profile:
                    torch.cuda.synchronize()
                t_bwd1 = time.time()
                optimizer.step()
            if sync_profile:
                torch.cuda.synchronize()
            t_step1 = time.time()

            # Metrics
            l = float(loss.item())
            r = float(recon_loss.item())
            m = float(mmd_loss.item())
            t = float(triplet_loss.item())
            epoch_loss += l
            epoch_recon += r
            epoch_mmd += m
            epoch_triplet += t
            # Train SSE/MSE accum
            try:
                sse_batch = torch.sum((recon_x - x) ** 2).item()
                train_sse_sum += float(sse_batch)
                train_elem_sum += int(x.numel())
            except Exception:
                pass
            num_batches += 1
            global_step += 1

            # Optional per-step profiling for first N steps
            if profile_n > 0 and step_idx < profile_n:
                bs = int(x.size(0))
                # Times
                dt_h2d = max(1e-9, t_h2d1 - t_h2d0)
                dt_fwd = max(1e-9, t_fwd1 - t_fwd0)
                dt_bwd = max(1e-9, t_bwd1 - t_bwd0)
                dt_wall = max(1e-9, t_step1 - step_wall_t0)
                # Throughputs
                samples_per_s = bs / dt_wall
                mb_h2d = (x.numel() * x.element_size()) / 1e6
                h2d_gbps = (mb_h2d / dt_h2d) / 1024.0  # GB/s
                # CUDA memory stats (if CUDA)
                mem_alloc_mb = mem_max_mb = None
                if device.type == 'cuda':
                    try:
                        mem_alloc_mb = torch.cuda.memory_allocated() / (1024**2)
                        mem_max_mb = torch.cuda.max_memory_allocated() / (1024**2)
                    except Exception:
                        pass
                logger.info(
                    f"[Profile] epoch={epoch+1} step={step_idx+1} bs={bs} "
                    f"h2d={dt_h2d*1000:.2f}ms fwd={dt_fwd*1000:.2f}ms bwd={dt_bwd*1000:.2f}ms "
                    f"wall={dt_wall*1000:.2f}ms thr={samples_per_s:.1f} samples/s "
                    f"H2D~{h2d_gbps:.2f} GB/s mem={mem_alloc_mb:.0f}/{mem_max_mb:.0f} MiB"
                )
                # Log to W&B as well
                if not args.no_wandb:
                    wandb.log({
                        'profile/h2d_ms': dt_h2d * 1000.0,
                        'profile/fwd_ms': dt_fwd * 1000.0,
                        'profile/bwd_ms': dt_bwd * 1000.0,
                        'profile/wall_ms': dt_wall * 1000.0,
                        'profile/samples_per_s': samples_per_s,
                        'profile/h2d_GBps': h2d_gbps,
                        'profile/mem_alloc_MiB': mem_alloc_mb,
                        'profile/mem_max_MiB': mem_max_mb,
                        'global_step': global_step,
                        'epoch': epoch,
                    })
                step_idx += 1

            if args.log_steps:
                writer.add_scalar('Loss/train_step', l, global_step)
                writer.add_scalar('Loss/recon_step', r, global_step)
                writer.add_scalar('Loss/mmd_step', m, global_step)
                writer.add_scalar('Loss/triplet_step', t, global_step)
                if not args.no_wandb:
                    wandb.log({
                        'Loss/train_step': l,
                        'Loss/recon_step': r,
                        'Loss/mmd_step': m,
                        'Loss/triplet_step': t,
                        'global_step': global_step,
                    })

        # Epoch aggregates
        avg_loss = epoch_loss / max(1, num_batches)
        avg_recon = epoch_recon / max(1, num_batches)
        avg_mmd = epoch_mmd / max(1, num_batches)
        avg_triplet = epoch_triplet / max(1, num_batches)
        epoch_time = time.time() - epoch_t0

        # Validation
        model.eval()
        val_loss_sum = 0.0
        val_recon_sum = 0.0
        val_mmd_sum = 0.0
        val_triplet_sum = 0.0
        val_batches = 0
        val_l2_sum = 0.0  # RMSE accumulated per-batch
        # Val SSE/MSE accumulators
        val_sse_sum = 0.0
        val_elem_sum = 0
        with torch.no_grad():
            for batch in val_loader:
                x_cpu = batch[0]
                x = x_cpu.to(device, non_blocking=(device.type == 'cuda'))
                recon_x, z = model(x)
                loss, recon_loss, mmd_loss, triplet_loss = model.loss_function(recon_x, x, z)
                val_loss_sum += float(loss.item())
                val_recon_sum += float(recon_loss.item())
                val_mmd_sum += float(mmd_loss.item())
                val_triplet_sum += float(triplet_loss.item())
                # Calculate L2 error (RMSE per value)
                l2_error = torch.sqrt(torch.mean((recon_x - x) ** 2))
                val_l2_sum += float(l2_error.item())
                # SSE/MSE accumulators for exact RMSE over all elements
                try:
                    sse_batch = torch.sum((recon_x - x) ** 2).item()
                    val_sse_sum += float(sse_batch)
                    val_elem_sum += int(x.numel())
                except Exception:
                    pass
                val_batches += 1

        # ---- Aggregate validation metrics ----
        val_avg_loss = val_loss_sum / max(1, val_batches)
        val_avg_recon = val_recon_sum / max(1, val_batches)
        val_avg_mmd = val_mmd_sum / max(1, val_batches)
        val_avg_triplet = val_triplet_sum / max(1, val_batches)
        # Global RMSE over all elements (preferred); fallback to mean of per-batch RMSE
        train_rmse = (float(np.sqrt(train_sse_sum / train_elem_sum)) if train_elem_sum > 0 else None)
        val_rmse = (float(np.sqrt(val_sse_sum / val_elem_sum)) if val_elem_sum > 0 else (val_l2_sum / max(1, val_batches)))

        # ---- Epoch summary & logging ----
        elapsed = epoch_time
        remaining_epochs = (num_epochs - (epoch + 1))
        eta_total_sec = elapsed * remaining_epochs
        eta_min = int(eta_total_sec // 60)
        eta_sec = int(eta_total_sec % 60)

        # Deltas vs previous
        msg = (
            f"Epoch {epoch+1}/{num_epochs}: "
            f"train_loss={avg_loss:.6f}{_fmt_delta(avg_loss, prev_metrics.get('train_loss'))} "
            f"recon={avg_recon:.6f}{_fmt_delta(avg_recon, prev_metrics.get('train_recon'))} "
            f"mmd={avg_mmd:.6f}{_fmt_delta(avg_mmd, prev_metrics.get('train_mmd'))} "
            f"triplet={avg_triplet:.6f}{_fmt_delta(avg_triplet, prev_metrics.get('train_triplet'))} "
            f"| val_loss={val_avg_loss:.6f}{_fmt_delta(val_avg_loss, prev_metrics.get('val_loss'))} "
            f"val_recon={val_avg_recon:.6f}{_fmt_delta(val_avg_recon, prev_metrics.get('val_recon'))} "
            f"val_mmd={val_avg_mmd:.6f}{_fmt_delta(val_avg_mmd, prev_metrics.get('val_mmd'))} "
            f"val_triplet={val_avg_triplet:.6f}{_fmt_delta(val_avg_triplet, prev_metrics.get('val_triplet'))} "
        )
        if train_rmse is not None:
            msg += f"| train_RMSE={train_rmse:.6f}{_fmt_delta(train_rmse, prev_metrics.get('train_rmSE'))} "
        msg += f"val_RMSE={val_rmse:.6f}{_fmt_delta(val_rmse, prev_metrics.get('val_rmSE'))} "
        msg += f"| epoch_time={elapsed:.2f}s | ETA~{eta_min}m{eta_sec:02d}s"

        print(_rainbow(msg))
        logger.info(msg)

        # TensorBoard scalars
        writer.add_scalar('epoch/train_loss', avg_loss, epoch+1)
        writer.add_scalar('epoch/train_recon', avg_recon, epoch+1)
        writer.add_scalar('epoch/train_mmd', avg_mmd, epoch+1)
        writer.add_scalar('epoch/train_triplet', avg_triplet, epoch+1)
        writer.add_scalar('epoch/val_loss', val_avg_loss, epoch+1)
        writer.add_scalar('epoch/val_recon', val_avg_recon, epoch+1)
        writer.add_scalar('epoch/val_mmd', val_avg_mmd, epoch+1)
        writer.add_scalar('epoch/val_triplet', val_avg_triplet, epoch+1)
        if train_rmse is not None:
            writer.add_scalar('epoch/train_RMSE', train_rmse, epoch+1)
        writer.add_scalar('epoch/val_RMSE', val_rmse, epoch+1)

        # W&B logging
        if not args.no_wandb:
            try:
                wandb.log({
                    'epoch': epoch + 1,
                    'global_step': global_step,
                    'epoch/train_loss': avg_loss,
                    'epoch/train_recon': avg_recon,
                    'epoch/train_mmd': avg_mmd,
                    'epoch/train_triplet': avg_triplet,
                    'epoch/val_loss': val_avg_loss,
                    'epoch/val_recon': val_avg_recon,
                    'epoch/val_mmd': val_avg_mmd,
                    'epoch/val_triplet': val_avg_triplet,
                    **({'epoch/train_RMSE': train_rmse} if train_rmse is not None else {}),
                    'epoch/val_RMSE': val_rmse,
                    'epoch/seconds': elapsed,
                })
            except Exception as e:
                logger.warning(f"wandb.log failed: {e}")

        # Update previous metrics for delta coloring
        prev_metrics = {
            'train_loss': avg_loss,
            'train_recon': avg_recon,
            'train_mmd': avg_mmd,
            'train_triplet': avg_triplet,
            'val_loss': val_avg_loss,
            'val_recon': val_avg_recon,
            'val_mmd': val_avg_mmd,
            'val_triplet': val_avg_triplet,
            'train_rmSE': train_rmse if train_rmse is not None else prev_metrics.get('train_rmSE'),
            'val_rmSE': val_rmse,
        }

        # ---- Checkpointing ----
        do_save = ((epoch + 1) % save_every == 0)
        if do_save:
            ckpt_path = os.path.join(save_dir, f"{MODEL_NAME}_epoch_{epoch+1}.pt")
            try:
                torch.save({
                    'model_state_dict': model.state_dict(),
                    'optimizer_state_dict': optimizer.state_dict(),
                    'scaler_state_dict': (scaler.state_dict() if (scaler is not None and use_amp) else None),
                    'epoch': epoch + 1,
                    'global_step': global_step,
                    'model_name': MODEL_NAME,
                    'accelerator': acc_info,
                }, ckpt_path)
                logger.info(f"Saved checkpoint: {ckpt_path}")
            except Exception as e:
                logger.warning(f"Failed to save checkpoint {ckpt_path}: {e}")

            # Prune older checkpoints in project dir
            try:
                prune_checkpoints(save_dir, MODEL_NAME, CHECKPOINTS_TO_KEEP)
            except Exception as e:
                logger.warning(f"prune_checkpoints failed: {e}")

            # Also copy into W&B run directory on Windows (symlink disabled)
            try:
                if not args.no_wandb and wandb_run is not None:
                    run_dir = getattr(wandb_run, 'dir', None)
                    if run_dir:
                        dst_dir = os.path.join(run_dir, 'files', 'saved_models')
                        os.makedirs(dst_dir, exist_ok=True)
                        shutil.copy2(ckpt_path, dst_dir)
                        logger.info(f"Copied checkpoint into W&B run dir: {dst_dir}")
                        prune_wandb_checkpoints_if_present(MODEL_NAME, CHECKPOINTS_TO_KEEP)
            except Exception as e:
                logger.warning(f"Failed to copy/prune W&B checkpoint: {e}")

    # end for epoch

    # Close writers
    try:
        writer.flush()
        writer.close()
    except Exception:
        pass

if __name__ == "__main__":
    # Entry point to start training when this script is executed directly
    main()
