#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Train WAE model 01 using prebuilt cached datasets (pickled NumPy arrays).

Overview
--------
This script is a sibling of `encoder/train_WAE_01.py` but, instead of
streaming random rows from many raw files via `EfficientDataLoader`, it
trains from two prebuilt, non-IO-bound datasets generated by
`build_autoencoder_dataset.py`:

- training_auto_encoder.pkl
- validation_auto_encoder.pkl

These files are expected to live under the directory pointed to by
`experiment.preferences -> root_path` (or a user-specified directory).
Each file contains a single NumPy array with shape:

    (num_rows, feature_dim)

Using these dense, contiguous arrays eliminates the file fan-out and
random-access overhead, enabling much faster training iterations.

Weights & Biases (wandb)
------------------------
We continue to log both per-epoch and optional per-step metrics to wandb.
On Windows, symlink creation is disabled for `wandb.save()` to avoid
WinError 1314; a best-effort file copy fallback is provided.

Usage examples
--------------
    # Default paths as specified in experiment.preferences
    python -m encoder.train_WAE_01_cached

    # Explicit filenames and batch size
    python -m encoder.train_WAE_01_cached \
        --train_file training_auto_encoder.pkl \
        --val_file   validation_auto_encoder.pkl \
        --batch_size 256

    # Resume from a checkpoint
    python -m encoder.train_WAE_01_cached --resume_checkpoint encoder/saved_models/WAE_Cached_001_final.pt

Notes
-----
- For very large cached arrays, ensure sufficient system RAM. You can
  use `--train_limit` / `--val_limit` to cap rows for quick experiments.
- The model architecture and loss are sourced from `encoder/model_WAE_01.py`.
"""

import os
import sys
import time
import logging
import argparse
import pickle
from typing import Optional, Tuple

import numpy as np
import torch
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from torch.utils.tensorboard import SummaryWriter

# Resolve project directories so we can import local modules
PARENT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PARENT_DIR not in sys.path:
    sys.path.append(PARENT_DIR)

from encoder.model_WAE_01 import WAE  # noqa: E402
from Ordered_001_Initialize import HostPreferences  # noqa: E402

# ----------------------
# Default training config
# ----------------------
MODEL_NAME = "WAE_Cached_001"
DEFAULT_BATCH_SIZE = 128
DEFAULT_EPOCHS = 5000
DEFAULT_LR = 1e-5
SAVE_INTERVAL = 10  # save every N epochs

# ----------
# Logging
# ----------
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# ================
# Accelerator utils
# ================
CSI = "\033["
RESET = f"{CSI}0m"
COLORS = [31, 33, 32, 36, 34, 35]  # R, Y, G, C, B, M

def _rainbow(msg: str) -> str:
    out = []
    k = 0
    for ch in msg:
        if ch.strip():
            out.append(f"{CSI}{COLORS[k % len(COLORS)]}m{ch}{RESET}")
            k += 1
        else:
            out.append(ch)
    return ''.join(out)


def accelerator_report() -> Tuple[torch.device, dict]:
    """Detect CUDA/MPS/CPU, print a colorful diagnostic, and return (device, info)."""
    pyv = torch.__version__
    try:
        import platform
        py = platform.python_version()
    except Exception:
        py = "?"

    has_cuda = torch.cuda.is_available()
    cuda_version = getattr(torch.version, 'cuda', None)
    mps_built = hasattr(torch.backends, 'mps') and torch.backends.mps.is_built()
    mps_avail = mps_built and torch.backends.mps.is_available()

    device = torch.device('cuda') if has_cuda else (torch.device('mps') if mps_avail else torch.device('cpu'))

    lines = [
        f"Python: {py} | PyTorch: {pyv}",
        f"CUDA available: {has_cuda} | CUDA toolkit: {cuda_version}",
        f"MPS built: {mps_built} | MPS available (runtime): {mps_avail}",
        f"Selected default device: {device}",
    ]

    if has_cuda:
        try:
            idx = torch.cuda.current_device()
            props = torch.cuda.get_device_properties(idx)
            cap = torch.cuda.get_device_capability(idx)
            lines += [
                f"CUDA device count: {torch.cuda.device_count()}",
                f"Current device: {idx} | Name: {props.name}",
                f"Compute capability: {cap[0]}.{cap[1]} | Total memory: {props.total_memory/1024**3:.2f} GiB",
            ]
        except Exception as e:
            lines.append(f"CUDA detail query failed: {e}")

    for ln in lines:
        print(_rainbow(ln))
        logger.info(ln)

    return device, {
        'python': py,
        'torch': pyv,
        'cuda_available': has_cuda,
        'cuda_version': cuda_version,
        'mps_built': mps_built,
        'mps_available': mps_avail,
        'selected_device': str(device),
    }


# ---------
# wandb
# ---------
import wandb  # noqa: E402


def _load_preferences(path: Optional[str]) -> HostPreferences:
    """Load HostPreferences from an explicit path or from project root by default."""
    if path is None:
        preferences_path = os.path.join(PARENT_DIR, "experiment.preferences")
    else:
        preferences_path = path
    prefs = HostPreferences(filename=preferences_path)
    # Adopt logging level if provided
    lvl = getattr(logging, getattr(prefs, 'logging_level', 'INFO').upper(), None)
    if isinstance(lvl, int):
        logger.setLevel(lvl)
        logger.info(f"Set logging level to {getattr(prefs, 'logging_level', 'INFO').upper()}")
    return prefs


def _load_cached_array(file_path: str, limit: Optional[int] = None) -> np.ndarray:
    """Load a pickled NumPy array from `file_path` and optionally cap rows.

    Ensures dtype float32 for compact storage and faster training.
    """
    t0 = time.time()
    with open(file_path, 'rb') as f:
        arr = pickle.load(f)
    if not isinstance(arr, np.ndarray):
        raise TypeError(f"Cached file {file_path} does not contain a NumPy array; got {type(arr)}")
    if arr.dtype != np.float32:
        arr = arr.astype(np.float32, copy=False)
    if limit is not None:
        arr = arr[:int(limit)]
    t1 = time.time()
    logger.info(f"Loaded cached array: {file_path} shape={arr.shape} dtype={arr.dtype} in {t1 - t0:.2f}s")
    return arr


def _make_loader(arr: np.ndarray, batch_size: int, shuffle: bool) -> DataLoader:
    """Wrap a NumPy array into a TensorDataset/DataLoader.

    - Uses pinned memory tensors on CUDA for faster H2D transfers.
    - Drop last is False to keep as many samples as possible per epoch.
    """
    # Create a torch tensor view (copies once from NumPy into a single big tensor)
    x_tensor = torch.from_numpy(arr)  # float32 ensured earlier
    dataset = TensorDataset(x_tensor)
    # We set pin_memory True; it is a no-op on CPU but accelerates CUDA H2D.
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=shuffle, pin_memory=True, drop_last=False)
    return loader


def main():
    parser = argparse.ArgumentParser(description="Train WAE model 01 using cached datasets (pickled arrays)")

    # Paths / files
    parser.add_argument('--preferences', type=str, default=None,
                        help='Path to experiment.preferences (defaults to project root).')
    parser.add_argument('--root', type=str, default=None,
                        help='Root directory that contains cached files; defaults to preferences.root_path')
    parser.add_argument('--train_file', type=str, default='training_auto_encoder.pkl',
                        help='Training cached filename (under --root).')
    parser.add_argument('--val_file', type=str, default='validation_auto_encoder.pkl',
                        help='Validation cached filename (under --root).')

    # Training hyperparameters
    parser.add_argument('--batch_size', type=int, default=DEFAULT_BATCH_SIZE)
    parser.add_argument('--epochs', type=int, default=DEFAULT_EPOCHS)
    parser.add_argument('--learning_rate', type=float, default=DEFAULT_LR)
    parser.add_argument('--save_interval', type=int, default=SAVE_INTERVAL)

    # Fast debug / limits
    parser.add_argument('--fast_debug', action='store_true', help='Use tiny settings for quick runs')
    parser.add_argument('--train_limit', type=int, default=None, help='Cap number of training rows (subset).')
    parser.add_argument('--val_limit', type=int, default=None, help='Cap number of validation rows (subset).')

    # Checkpointing / logging
    parser.add_argument('--resume_checkpoint', type=str, default=None,
                        help='Path to a checkpoint .pt file to resume from.')
    parser.add_argument('--no_wandb', action='store_true', help='Disable Weights & Biases logging')

    # Step logging verbosity
    parser.add_argument('--log_steps', action='store_true', help='Log per-step losses to TensorBoard (and W&B).')

    args = parser.parse_args()

    # Preferences and roots
    prefs = _load_preferences(args.preferences)
    root_dir = args.root or getattr(prefs, 'root_path', os.getcwd())

    # Resolve file paths
    train_path = os.path.join(root_dir, args.train_file)
    val_path = os.path.join(root_dir, args.val_file)

    if not os.path.isfile(train_path):
        raise FileNotFoundError(f"Training cached file not found: {train_path}")
    if not os.path.isfile(val_path):
        raise FileNotFoundError(f"Validation cached file not found: {val_path}")

    # Effective settings
    batch_size = int(args.batch_size)
    num_epochs = int(args.epochs)
    lr = float(args.learning_rate)
    save_every = max(1, int(args.save_interval))

    if args.fast_debug:
        # Keep memory/time small for quick iteration
        num_epochs = min(1, num_epochs)
        batch_size = min(128, batch_size)
        if args.train_limit is None:
            args.train_limit = 10_000
        if args.val_limit is None:
            args.val_limit = 10_000
        logger.info("FAST DEBUG active: epochs=%s, batch_size=%s, train_limit=%s, val_limit=%s",
                    num_epochs, batch_size, args.train_limit, args.val_limit)

    # -------- wandb: run init & notes --------
    wandb_run = None
    if not args.no_wandb:
        # Try to include the model source code as 'notes' to the run for convenience
        notes_content = ""
        model_filepath = os.path.join(PARENT_DIR, 'encoder', 'model_WAE_01.py')
        try:
            with open(model_filepath, 'r') as f:
                notes_content = f.read()
        except Exception as e:
            notes_content = f"Failed to load model file: {e}"

        # On Windows, disable symlinks to avoid WinError 1314 during wandb.save
        try:
            import platform
            is_windows = platform.system().lower().startswith('win')
        except Exception:
            is_windows = False

        wandb_run = wandb.init(
            project=MODEL_NAME,
            name=f"{MODEL_NAME}_run",
            notes=notes_content,
            config={
                'model': MODEL_NAME,
                'batch_size': batch_size,
                'epochs': num_epochs,
                'learning_rate': lr,
                'train_path': train_path,
                'val_path': val_path,
            },
            settings=wandb.Settings(symlink=not is_windows)
        )

    # Device setup & diagnostic
    device, acc_info = accelerator_report()
    try:
        if not args.no_wandb:
            wandb.config.update({'accelerator': acc_info}, allow_val_change=True)
    except Exception:
        pass

    # Output directories (relative to this script working directory)
    save_dir = os.path.join(PARENT_DIR, 'encoder', 'saved_models')
    log_dir = os.path.join(PARENT_DIR, 'encoder', 'logs')
    os.makedirs(save_dir, exist_ok=True)
    os.makedirs(log_dir, exist_ok=True)

    # TensorBoard writer
    writer = SummaryWriter(log_dir=log_dir)

    # ------------------
    # Data: load & wrap
    # ------------------
    train_np = _load_cached_array(train_path, limit=args.train_limit)
    val_np = _load_cached_array(val_path, limit=args.val_limit)

    train_loader = _make_loader(train_np, batch_size=batch_size, shuffle=True)
    val_loader = _make_loader(val_np, batch_size=batch_size, shuffle=False)

    # Free NumPy arrays early to reduce memory pressure; data now lives in tensors.
    del train_np
    del val_np

    # ---------------
    # Model & optim
    # ---------------
    model = WAE().to(device)
    try:
        if device.type == 'cuda':
            torch.backends.cudnn.benchmark = True
    except Exception:
        pass
    optimizer = optim.Adam(model.parameters(), lr=lr)

    start_epoch = 0

    # Optional: resume from checkpoint
    resume_path = args.resume_checkpoint
    if resume_path is None:
        # Convenience default: try the model's final checkpoint name in save_dir
        default_final = os.path.join(save_dir, f"{MODEL_NAME}_final.pt")
        if os.path.isfile(default_final):
            resume_path = default_final
    if resume_path and os.path.isfile(resume_path):
        try:
            logger.info(f"Loading checkpoint from {resume_path}")
            checkpoint = torch.load(resume_path, map_location=device)
            model.load_state_dict(checkpoint['model_state_dict'])
            if 'optimizer_state_dict' in checkpoint:
                optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
            if 'epoch' in checkpoint:
                start_epoch = int(checkpoint['epoch'])
                logger.info(f"Resuming training from epoch {start_epoch}")
        except Exception as e:
            logger.error(f"Failed to load checkpoint: {e}")
            logger.error("Training will start from scratch.")

    logger.info(f"Initialized WAE model with latent dimension {model.fc4.out_features}")

    # =================
    # Training routine
    # =================
    global_step = 0
    train_start = time.time()

    for epoch in range(start_epoch, num_epochs):
        model.train()
        epoch_loss = 0.0
        epoch_recon = 0.0
        epoch_mmd = 0.0
        epoch_triplet = 0.0
        num_batches = 0
        epoch_t0 = time.time()

        for batch in train_loader:
            # batch is a tuple from TensorDataset
            x_cpu = batch[0]
            # Move to device; `pin_memory=True` at loader level enables non_blocking
            x = x_cpu.to(device, non_blocking=(device.type == 'cuda'))

            # Forward
            recon_x, z = model(x)
            # Loss
            loss, recon_loss, mmd_loss, triplet_loss = model.loss_function(recon_x, x, z)

            # Backward
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            # Metrics
            l = float(loss.item())
            r = float(recon_loss.item())
            m = float(mmd_loss.item())
            t = float(triplet_loss.item())
            epoch_loss += l
            epoch_recon += r
            epoch_mmd += m
            epoch_triplet += t
            num_batches += 1
            global_step += 1

            if args.log_steps:
                writer.add_scalar('Loss/train_step', l, global_step)
                writer.add_scalar('Loss/recon_step', r, global_step)
                writer.add_scalar('Loss/mmd_step', m, global_step)
                writer.add_scalar('Loss/triplet_step', t, global_step)
                if not args.no_wandb:
                    wandb.log({
                        'Loss/train_step': l,
                        'Loss/recon_step': r,
                        'Loss/mmd_step': m,
                        'Loss/triplet_step': t,
                        'global_step': global_step,
                    })

        # Epoch aggregates
        avg_loss = epoch_loss / max(1, num_batches)
        avg_recon = epoch_recon / max(1, num_batches)
        avg_mmd = epoch_mmd / max(1, num_batches)
        avg_triplet = epoch_triplet / max(1, num_batches)
        epoch_time = time.time() - epoch_t0

        # Validation
        model.eval()
        val_loss_sum = 0.0
        val_recon_sum = 0.0
        val_mmd_sum = 0.0
        val_triplet_sum = 0.0
        val_batches = 0
        with torch.no_grad():
            for batch in val_loader:
                x_cpu = batch[0]
                x = x_cpu.to(device, non_blocking=(device.type == 'cuda'))
                recon_x, z = model(x)
                loss, recon_loss, mmd_loss, triplet_loss = model.loss_function(recon_x, x, z)
                val_loss_sum += float(loss.item())
                val_recon_sum += float(recon_loss.item())
                val_mmd_sum += float(mmd_loss.item())
                val_triplet_sum += float(triplet_loss.item())
                val_batches += 1

        val_loss = val_loss_sum / max(1, val_batches)
        val_recon = val_recon_sum / max(1, val_batches)
        val_mmd = val_mmd_sum / max(1, val_batches)
        val_triplet = val_triplet_sum / max(1, val_batches)

        logger.info(
            f"Epoch {epoch + 1}/{num_epochs} | "
            f"Train: Loss {avg_loss:.6f} | Recon {avg_recon:.6f} | MMD {avg_mmd:.6f} | Triplet {avg_triplet:.6f} | "
            f"Val: Loss {val_loss:.6f} | Recon {val_recon:.6f} | MMD {val_mmd:.6f} | Triplet {val_triplet:.6f} | "
            f"Time {epoch_time:.2f}s"
        )

        # TensorBoard (per-epoch)
        writer.add_scalar('Loss/train_epoch', avg_loss, epoch)
        writer.add_scalar('Loss/recon_epoch', avg_recon, epoch)
        writer.add_scalar('Loss/mmd_epoch', avg_mmd, epoch)
        writer.add_scalar('Loss/triplet_epoch', avg_triplet, epoch)

        writer.add_scalar('Val/Loss_epoch', val_loss, epoch)
        writer.add_scalar('Val/recon_epoch', val_recon, epoch)
        writer.add_scalar('Val/mmd_epoch', val_mmd, epoch)
        writer.add_scalar('Val/triplet_epoch', val_triplet, epoch)

        # W&B (per-epoch)
        if not args.no_wandb:
            wandb.log({
                'Loss/train_epoch': avg_loss,
                'Loss/recon_epoch': avg_recon,
                'Loss/mmd_epoch': avg_mmd,
                'Loss/triplet_epoch': avg_triplet,
                'Val/Loss_epoch': val_loss,
                'Val/recon_epoch': val_recon,
                'Val/mmd_epoch': val_mmd,
                'Val/triplet_epoch': val_triplet,
                'epoch': epoch,
            })

        # Save checkpoint
        if (epoch + 1) % save_every == 0:
            ckpt_path = os.path.join(save_dir, f"{MODEL_NAME}_epoch_{epoch + 1}.pt")
            torch.save({
                'epoch': epoch + 1,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'loss': avg_loss,
                'val_loss': val_loss,
            }, ckpt_path)
            logger.info(f"Saved model checkpoint to {ckpt_path}")
            if not args.no_wandb:
                try:
                    wandb.save(ckpt_path)
                except OSError as e:
                    logger.warning(f"wandb.save failed (likely symlink issue on Windows): {e}")
                    try:
                        import shutil
                        run_dir = wandb.run.dir if wandb.run else None
                        if run_dir:
                            dst_dir = os.path.join(run_dir, 'files', 'saved_models')
                            os.makedirs(dst_dir, exist_ok=True)
                            dst_path = os.path.join(dst_dir, os.path.basename(ckpt_path))
                            shutil.copy2(ckpt_path, dst_path)
                            logger.info(f"Copied checkpoint to W&B files dir: {dst_path}")
                    except Exception as e2:
                        logger.error(f"Failed to copy checkpoint into W&B dir: {e2}")

    # Final save
    final_path = os.path.join(save_dir, f"{MODEL_NAME}_final.pt")
    torch.save({
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
    }, final_path)
    logger.info(f"Saved final model to {final_path}")
    if not args.no_wandb:
        try:
            wandb.save(final_path)
        except OSError as e:
            logger.warning(f"wandb.save (final) failed (likely symlink issue on Windows): {e}")
            try:
                import shutil
                run_dir = wandb.run.dir if wandb.run else None
                if run_dir:
                    dst_dir = os.path.join(run_dir, 'files', 'saved_models')
                    os.makedirs(dst_dir, exist_ok=True)
                    dst_path = os.path.join(dst_dir, os.path.basename(final_path))
                    shutil.copy2(final_path, dst_path)
                    logger.info(f"Copied final model to W&B files dir: {dst_path}")
            except Exception as e2:
                logger.error(f"Failed to copy final model into W&B dir: {e2}")

    total_time = time.time() - train_start
    logger.info(f"Training completed in {total_time:.2f} seconds")

    writer.close()
    if not args.no_wandb:
        wandb.finish()


if __name__ == "__main__":
    main()
