#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Train WAE model 01 using prebuilt cached datasets (pickled NumPy arrays).
Overview
--------
This script is a sibling of `encoder/train_WAE_01.py` but, instead of
streaming random rows from many raw files via `EfficientDataLoader`, it
trains from two prebuilt, non-IO-bound datasets generated by
`build_autoencoder_dataset.py`:

- training_auto_encoder.pkl
- validation_auto_encoder.pkl

These files are expected to live under the directory pointed to by
`experiment.preferences -> root_path` (or a user-specified directory).
Each file contains a single NumPy array with shape:

    (num_rows, feature_dim)

Using these dense, contiguous arrays eliminates the file fan-out and
random-access overhead, enabling much faster training iterations.

Weights & Biases (wandb)
------------------------
We continue to log both per-epoch and optional per-step metrics to wandb.
On Windows, symlink creation is disabled for `wandb.save()` to avoid
WinError 1314; a best-effort file copy fallback is provided.

Usage examples
--------------
    # Default paths as specified in experiment.preferences
    python -m encoder.train_WAE_01_cached

    # Explicit filenames and batch size
    python -m encoder.train_WAE_01_cached \
        --train_file training_auto_encoder.pkl \
        --val_file   validation_auto_encoder.pkl \
        --batch_size 256

    # Resume from a checkpoint
    python -m encoder.train_WAE_01_cached --resume_checkpoint encoder/saved_models/WAE_Cached_001_final.pt

Notes
-----
- For very large cached arrays, ensure sufficient system RAM. You can
  use `--train_limit` / `--val_limit` to cap rows for quick experiments.
- The model architecture and loss are sourced from `encoder/model_WAE_01.py`.
"""

import os
import sys
import time
import logging
import argparse
import pickle
import re
import glob
import shutil
from typing import Optional, Tuple
import hashlib
import random

import numpy as np
import torch
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from torch.utils.tensorboard import SummaryWriter

# Resolve project directories so we can import local modules
PARENT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PARENT_DIR not in sys.path:
    sys.path.append(PARENT_DIR)

from encoder.model_WAE_01 import WAE  # noqa: E402
from Ordered_001_Initialize import HostPreferences  # noqa: E402

# ----------------------
# Default training config
# ----------------------
MODEL_NAME = "WAE_Cached_012_H200"
DEFAULT_BATCH_SIZE = 128
DEFAULT_EPOCHS = 5500
DEFAULT_LR = 1e-6
SAVE_INTERVAL = 2  # save every N epochs
CHECKPOINTS_TO_KEEP = 5  # keep last K rolling checkpoints

# ----------
# Logging
# ----------
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# ================
# Accelerator utils
# ================
CSI = "\033["
RESET = f"{CSI}0m"
COLORS = [31, 33, 32, 36, 34, 35]  # R, Y, G, C, B, M
GREEN = f"{CSI}32m"
RED = f"{CSI}31m"
GREY = f"{CSI}90m"


def _rainbow(msg: str) -> str:
    out = []
    k = 0
    for ch in msg:
        if ch.strip():
            out.append(f"{CSI}{COLORS[k % len(COLORS)]}m{ch}{RESET}")
            k += 1
        else:
            out.append(ch)
    return ''.join(out)


def _fmt_delta(curr: float, prev: float | None, *, lower_is_better: bool = True, suffix: str = "", decimals: int = 3, color_enabled: bool = True) -> str:
    """Return a colored delta string like ' (-0.001)' with green for improvement and red for regression.
    If prev is None, return empty string. Uses subtle color only for the delta when color_enabled is True; otherwise plain text.
    """
    try:
        if prev is None:
            return ""
        diff = curr - prev
        sign = "+" if diff > 0 else ("-" if diff < 0 else "±")
        val = format(abs(diff), f".{decimals}f")
        if not color_enabled or diff == 0:
            return f" ({sign}{val}{suffix})"
        color = GREEN if ((diff < 0) == lower_is_better) else RED
        return f" ({color}{sign}{val}{suffix}{RESET})"
    except Exception:
        return ""


def _fmt_val(v: float, decimals: int = 3) -> str:
    """Format a float with 3 decimals by default; switch to scientific for very large/small magnitudes."""
    try:
        av = abs(float(v))
        if av >= 1e6 or (av != 0 and av < 1e-3):
            return format(v, f".{decimals}e")
        return format(v, f".{decimals}f")
    except Exception:
        return str(v)


def accelerator_report() -> Tuple[torch.device, dict]:
    """Detect CUDA/MPS/CPU, print a diagnostic, and return (device, info).

    Returns
    -------
    (device, info_dict)
        device: torch.device selected as default
        info_dict: summary fields for logging/W&B
    """
    pyv = torch.__version__
    try:
        import platform
        py = platform.python_version()
    except Exception:
        py = "?"

    # Probe accelerators
    has_cuda = torch.cuda.is_available()
    cuda_version = getattr(torch.version, 'cuda', None)
    mps_built = hasattr(torch.backends, 'mps') and torch.backends.mps.is_built()
    mps_avail = mps_built and torch.backends.mps.is_available()

    device = torch.device('cuda') if has_cuda else (torch.device('mps') if mps_avail else torch.device('cpu'))

    # Compose lines
    lines = [
        f"Python: {py} | PyTorch: {pyv}",
        f"CUDA available: {has_cuda} | CUDA toolkit: {cuda_version}",
        f"MPS built: {mps_built} | MPS available (runtime): {mps_avail}",
        f"Selected default device: {device}",
    ]

    if has_cuda:
        try:
            idx = torch.cuda.current_device()
            props = torch.cuda.get_device_properties(idx)
            cap = torch.cuda.get_device_capability(idx)
            lines += [
                f"CUDA device count: {torch.cuda.device_count()}",
                f"Current device: {idx} | Name: {props.name}",
                f"Compute capability: {cap[0]}.{cap[1]} | Total memory: {props.total_memory/1024**3:.2f} GiB",
            ]
        except Exception as e:
            lines.append(f"CUDA detail query failed: {e}")

    # Log once (avoid duplicate console output)
    for ln in lines:
        logger.info(ln)

    return device, {
        'python': py,
        'torch': pyv,
        'cuda_available': has_cuda,
        'cuda_version': cuda_version,
        'mps_built': mps_built,
        'mps_available': mps_avail,
        'selected_device': str(device),
    }


def _model_checksum(model: torch.nn.Module) -> Tuple[float, float]:
    """Compute a simple checksum of model parameters on CPU: (sum, abs_sum)."""
    s = 0.0
    a = 0.0
    try:
        with torch.no_grad():
            for p in model.parameters():
                t = p.detach().float().cpu()
                s += float(t.sum().item())
                a += float(t.abs().sum().item())
    except Exception:
        pass
    return float(s), float(a)



# ---------
# wandb
# ---------
import wandb  # noqa: E402


def _parse_epoch_from_filename(filename: str, model_name: str) -> Optional[int]:
    """Extract epoch number from a checkpoint filename of the form
    f"{model_name}_epoch_<N>.pt". Returns None if no match.
    """
    try:
        base = os.path.basename(filename)
        m = re.match(rf"{re.escape(model_name)}_epoch_(\d+)\.pt$", base)
        if m:
            return int(m.group(1))
    except Exception:
        pass
    return None


essential_ckpt_patterns = (
    # anything named *_final.pt should never be pruned
    "_final.pt",
)


def prune_checkpoints(dir_path: str, model_name: str, keep: int) -> None:
    """Keep only the newest `keep` epoch checkpoints in `dir_path` for `model_name`.

    - Matches files like f"{model_name}_epoch_*.pt"
    - Excludes any file that ends with "_final.pt"
    - Deletes oldest files first, keeping at most `keep` newest.
    - Best-effort; logs and continues on errors.
    """
    try:
        pattern = os.path.join(dir_path, f"{model_name}_epoch_*.pt")
        files = glob.glob(pattern)
        if not files:
            return
        # Exclude any accidental finals
        files = [f for f in files if not f.endswith("_final.pt")]
        # Build list of (epoch, path)
        items = []
        for fpath in files:
            ep = _parse_epoch_from_filename(fpath, model_name)
            if ep is not None:
                items.append((ep, fpath))
        if not items:
            return
        items.sort(key=lambda x: x[0])  # ascending by epoch
        # Determine which to delete
        to_delete = items[:-keep] if keep > 0 else items
        for ep, fpath in to_delete:
            try:
                os.remove(fpath)
                logger.info(f"Pruned old checkpoint (epoch {ep}): {fpath}")
            except Exception as e:
                logger.warning(f"Failed to remove old checkpoint {fpath}: {e}")
    except Exception as e:
        logger.warning(f"prune_checkpoints failed for {dir_path}: {e}")


def prune_wandb_checkpoints_if_present(model_name: str, keep: int) -> None:
    """Prune checkpoint copies inside the current W&B run directory (Windows copy fallback).

    We mirror the location used in the fallback copy: wandb.run.dir/files/saved_models
    """
    try:
        run = getattr(wandb, 'run', None)
        if not run:
            return
        run_dir = getattr(run, 'dir', None)
        if not run_dir:
            return
        dst_dir = os.path.join(run_dir, 'files', 'saved_models')
        if os.path.isdir(dst_dir):
            prune_checkpoints(dst_dir, model_name, keep)
    except Exception as e:
        logger.warning(f"prune_wandb_checkpoints_if_present failed: {e}")


def _load_preferences(path: Optional[str]) -> HostPreferences:
    """Load HostPreferences from an explicit path or from project root by default."""
    if path is None:
        preferences_path = os.path.join(PARENT_DIR, "experiment.preferences")
    else:
        preferences_path = path
    prefs = HostPreferences(filename=preferences_path)
    # Adopt logging level if provided
    lvl = getattr(logging, getattr(prefs, 'logging_level', 'INFO').upper(), None)
    if isinstance(lvl, int):
        logger.setLevel(lvl)
        logger.info(f"Set logging level to {getattr(prefs, 'logging_level', 'INFO').upper()}")
    return prefs


def _load_cached_array(file_path: str, limit: Optional[int] = None) -> np.ndarray:
    """Load a pickled NumPy array from `file_path` and optionally cap rows.

    Ensures dtype float32 for compact storage and faster training.
    """
    t0 = time.time()
    with open(file_path, 'rb') as f:
        arr = pickle.load(f)
    if not isinstance(arr, np.ndarray):
        raise TypeError(f"Cached file {file_path} does not contain a NumPy array; got {type(arr)}")
    if arr.dtype != np.float32:
        arr = arr.astype(np.float32, copy=False)
    if limit is not None:
        arr = arr[:int(limit)]
    t1 = time.time()
    logger.info(f"Loaded cached array: {file_path} shape={arr.shape} dtype={arr.dtype} in {t1 - t0:.2f}s")
    return arr


def _make_loader(
        arr: np.ndarray,
        batch_size: int,
        shuffle: bool,
        num_workers: int = 0,
        prefetch_factor: int = 2,
        persistent_workers: bool = False,
        pin_memory: bool = True,
    ) -> DataLoader:
    """Wrap a NumPy array into a TensorDataset/DataLoader.

    - Uses pinned memory tensors on CUDA for faster H2D transfers.
    - Drop last is False to keep as many samples as possible per epoch.
    - Supports multi-worker prefetch to keep the GPU fed.
    """
    # Create a torch tensor view (copies once from NumPy into a single big tensor)
    x_tensor = torch.from_numpy(arr)  # float32 ensured earlier
    dataset = TensorDataset(x_tensor)

    # persistent_workers is only valid when num_workers > 0
    use_persistent = bool(persistent_workers and num_workers > 0)

    # On CPU-only runs, pin_memory has no effect; on CUDA it accelerates H2D
    loader_kwargs = dict(
        batch_size=batch_size,
        shuffle=shuffle,
        pin_memory=pin_memory,
        drop_last=False,
        num_workers=max(0, int(num_workers)),
        persistent_workers=use_persistent,
    )
    if int(num_workers) > 0:
        loader_kwargs['prefetch_factor'] = int(prefetch_factor)
    loader = DataLoader(
        dataset,
        **loader_kwargs,
    )
    return loader


# ---- Provenance & checksum helpers ----

def _count_params(model: torch.nn.Module) -> int:
    try:
        return sum(p.numel() for p in model.parameters())
    except Exception:
        return -1


def _optimizer_checksum(optimizer: optim.Optimizer) -> Tuple[float, float]:
    """Compute a simple checksum across optimizer state tensors: (sum, abs_sum)."""
    s = 0.0
    a = 0.0
    try:
        with torch.no_grad():
            for state in optimizer.state.values():
                for v in state.values():
                    if isinstance(v, torch.Tensor):
                        t = v.detach().float().cpu()
                        s += float(t.sum().item())
                        a += float(t.abs().sum().item())
    except Exception:
        pass
    return float(s), float(a)


def _file_info(path: str) -> dict:
    try:
        exists = os.path.exists(path)
        size = os.path.getsize(path) if exists else None
        mtime = os.path.getmtime(path) if exists else None
        return {'exists': bool(exists), 'size': size, 'mtime': mtime}
    except Exception:
        return {'exists': False, 'size': None, 'mtime': None}


# -------- Evaluation helper --------

def _sha256_file(path: str, chunk_size: int = 4 * 1024 * 1024) -> Optional[str]:
    try:
        h = hashlib.sha256()
        with open(path, 'rb') as f:
            while True:
                b = f.read(chunk_size)
                if not b:
                    break
                h.update(b)
        return h.hexdigest()
    except Exception:
        return None

def _set_deterministic(seed: int = 12345) -> None:
    try:
        np.random.seed(seed)
    except Exception:
        pass
    try:
        random.seed(seed)
    except Exception:
        pass
    try:
        torch.manual_seed(seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(seed)
        try:
            torch.use_deterministic_algorithms(True)
        except Exception:
            pass
        try:
            torch.backends.cudnn.deterministic = True
            torch.backends.cudnn.benchmark = False
        except Exception:
            pass
    except Exception:
        pass

def _evaluate_full(model: torch.nn.Module, loader: DataLoader, device: torch.device, *, audit: bool = False) -> dict:
    """Run a full pass over `loader` computing the same aggregates the epoch loop uses.
    Returns a dict with keys: loss, recon, mmd, triplet, rmse, batches.
    If audit=True, also returns 'audit' sub-dict with alternative deterministic aggregations.
    """
    model_was_training = model.training
    model.eval()
    loss_sum = recon_sum = mmd_sum = triplet_sum = 0.0
    batches = 0
    sse_sum = 0.0
    elem_sum = 0
    sample_count = 0

    # Audit accumulators
    audit_total_recon_logcosh_sum = 0.0  # sum over all instances of sum(logcosh) -> for mean over instances
    audit_total_triplet63_sum = 0.0      # mean-of-instances triplet (index 62) sum across instances
    audit_instances_count = 0
    audit_max_recon_across_set = None

    with torch.no_grad():
        for batch in loader:
            x_cpu = batch[0]
            x = x_cpu.to(device, non_blocking=(device.type == 'cuda'))
            bs = int(x.size(0))
            sample_count += bs
            recon_x, z = model(x)
            loss, recon_loss, mmd_loss, triplet_loss = model.loss_function(recon_x, x, z)
            loss_sum += float(loss.item())
            recon_sum += float(recon_loss.item())
            mmd_sum += float(mmd_loss.item())
            triplet_sum += float(triplet_loss.item())
            try:
                sse_batch = torch.sum((recon_x - x) ** 2).item()
                sse_sum += float(sse_batch)
                elem_sum += int(x.numel())
            except Exception:
                pass

            if audit:
                try:
                    # Recompute per-instance log-cosh with the same scaling (10) used in model.log_cosh_loss
                    prediction_error = x - recon_x
                    scaled_error = 10.0 * prediction_error
                    lc = torch.log(torch.cosh(scaled_error))
                    # sum over feature dim
                    lc_inst = torch.sum(lc.view(bs, -1), dim=1)
                    audit_total_recon_logcosh_sum += float(lc_inst.sum().item())
                    audit_instances_count += bs
                    m_inst = float(lc_inst.max().item())
                    if (audit_max_recon_across_set is None) or (m_inst > audit_max_recon_across_set):
                        audit_max_recon_across_set = m_inst
                    # Triplet mean over instances at fixed index 62 (if divisible by 3 as expected)
                    try:
                        grouped = recon_x.view(bs, -1, 3)
                        grouped_x = x.view(bs, -1, 3)
                        if grouped.size(1) > 62:
                            trip_inst = torch.mean((grouped[:, 62] - grouped_x[:, 62]) ** 2, dim=1)  # per-instance MSE of index 62
                            audit_total_triplet63_sum += float(trip_inst.sum().item())
                    except Exception:
                        pass
                except Exception:
                    pass

            batches += 1
    if model_was_training:
        model.train()
    avg_loss = loss_sum / max(1, batches)
    avg_recon = recon_sum / max(1, batches)
    avg_mmd = mmd_sum / max(1, batches)
    avg_triplet = triplet_sum / max(1, batches)
    rmse = float(np.sqrt(sse_sum / elem_sum)) if elem_sum > 0 else float('nan')

    out = {
        'loss': avg_loss,
        'recon': avg_recon,
        'mmd': avg_mmd,
        'triplet': avg_triplet,
        'rmse': rmse,
        'batches': batches,
    }
    if audit:
        mean_recon_logcosh_per_instance = (audit_total_recon_logcosh_sum / audit_instances_count) if audit_instances_count > 0 else float('nan')
        mean_triplet63_per_instance = (audit_total_triplet63_sum / audit_instances_count) if audit_instances_count > 0 else float('nan')
        out['audit'] = {
            'instances': audit_instances_count,
            'elements': elem_sum,
            'loss_sum_over_batches': loss_sum,
            'recon_sum_over_batches': recon_sum,
            'mmd_sum_over_batches': mmd_sum,
            'triplet_sum_over_batches': triplet_sum,
            'mean_recon_logcosh_per_instance': mean_recon_logcosh_per_instance,
            'max_recon_logcosh_over_set': (float(audit_max_recon_across_set) if audit_max_recon_across_set is not None else None),
            'mean_triplet63_mse_per_instance': mean_triplet63_per_instance,
            'rmse': rmse,
            'mse': (rmse * rmse) if np.isfinite(rmse) else float('nan'),
            'samples': sample_count,
        }
    return out


def _build_provenance(model: torch.nn.Module,
                      optimizer: optim.Optimizer,
                      acc_info: dict,
                      args,
                      *,
                      model_name: str,
                      train_path: str,
                      val_path: str,
                      num_epochs: int,
                      batch_size: int,
                      lr: float,
                      save_every: int) -> dict:
    try:
        import platform
        host = platform.node()
    except Exception:
        host = None
    # Checksums
    m_sum, m_abs = _model_checksum(model)
    o_sum, o_abs = _optimizer_checksum(optimizer)
    # Hashes
    train_sha = _sha256_file(train_path)
    val_sha = _sha256_file(val_path)
    # Build dict
    # Model source file info
    model_src_path = os.path.join(PARENT_DIR, 'encoder', 'model_WAE_01.py')
    try:
        model_src_sha = _sha256_file(model_src_path)
        model_src_info = {
            'path': model_src_path,
            'sha256': model_src_sha,
            'size': os.path.getsize(model_src_path) if os.path.exists(model_src_path) else None,
            'mtime': os.path.getmtime(model_src_path) if os.path.exists(model_src_path) else None,
        }
    except Exception:
        model_src_info = {'path': model_src_path, 'sha256': None, 'size': None, 'mtime': None}

    prov = {
        'timestamp': time.time(),
        'host': host,
        'python': acc_info.get('python'),
        'torch': acc_info.get('torch'),
        'cuda_version': acc_info.get('cuda_version'),
        'device': acc_info.get('selected_device'),
        'model_name': model_name,
        'param_count': _count_params(model),
        'model_checksum': {'sum': m_sum, 'abs_sum': m_abs},
        'optimizer_checksum': {'sum': o_sum, 'abs_sum': o_abs},
        'model_source': model_src_info,
        'run_config': {
            'epochs': int(num_epochs),
            'batch_size': int(batch_size),
            'learning_rate': float(lr),
            'save_interval': int(save_every),
            'amp': bool(getattr(args, 'amp', False)),
            'compile': bool(getattr(args, 'compile', False)),
            'width': int(getattr(args, 'width', 90) or 90),
            'no_color': bool(getattr(args, 'no_color', False)),
            'debug': bool(getattr(args, 'debug', False)),
            'num_workers': int(getattr(args, 'num_workers', 0)),
            'prefetch_factor': int(getattr(args, 'prefetch_factor', 2)),
            'persistent_workers': bool(getattr(args, 'persistent_workers', False)),
            'pin_memory': not bool(getattr(args, 'no_pin_memory', False)),
            'profile_steps': int(getattr(args, 'profile_steps', 0)),
            'sync_profile': bool(getattr(args, 'sync_profile', False)),
            'train_limit': (int(args.train_limit) if getattr(args, 'train_limit', None) is not None else None),
            'val_limit': (int(args.val_limit) if getattr(args, 'val_limit', None) is not None else None),
        },
        'data': {
            'train_path': train_path,
            'val_path': val_path,
            'train_file': {**_file_info(train_path), 'sha256': train_sha},
            'val_file': {**_file_info(val_path), 'sha256': val_sha},
            'train_limit': (int(args.train_limit) if getattr(args, 'train_limit', None) is not None else None),
            'val_limit': (int(args.val_limit) if getattr(args, 'val_limit', None) is not None else None),
        },
        'loss_config': {
            'recon': {
                'type': 'log_cosh',
                'scale_factor': 10,
                'reduction': 'max_over_instances_of_sum_per_instance',
            },
            'triplet': {
                'type': 'mse_single_index',
                'index': 62,
                'aggregation': 'random_single_instance_per_batch',
            },
            'mmd': {
                'type': 'kernel_mmd',
                'kernel': 'exp(-mean((x-y)^2)/dim*2)',
            },
            'composite': 'recon + mmd + triplet',
        },
        'metrics_definitions': {
            'rmse': 'global_per_element_over_full_set',
            'val_loss_epoch': 'mean_of_per_batch_total_loss_items',
        }
    }
    return prov


def main():
    parser = argparse.ArgumentParser(description="Train WAE model 01 using cached datasets (pickled arrays)")

    # Paths / files
    parser.add_argument('--preferences', type=str, default=None,
                        help='Path to experiment.preferences (defaults to project root).')
    parser.add_argument('--root', type=str, default=None,
                        help='Root directory that contains cached files; defaults to preferences.root_path')
    parser.add_argument('--train_file', type=str, default='training_auto_encoder.pkl',
                        help='Training cached filename (under --root).')
    parser.add_argument('--val_file', type=str, default='validation_auto_encoder.pkl',
                        help='Validation cached filename (under --root).')
    parser.add_argument('--test_file', type=str, default=None,
                        help='Optional test cached filename (under --root). If provided, evaluate RMSE after training.')

    # Training hyperparameters
    parser.add_argument('--batch_size', type=int, default=DEFAULT_BATCH_SIZE)
    parser.add_argument('--epochs', type=int, default=DEFAULT_EPOCHS)
    parser.add_argument('--learning_rate', type=float, default=DEFAULT_LR)
    parser.add_argument('--save_interval', type=int, default=SAVE_INTERVAL)

    # Output formatting / debug
    parser.add_argument('--width', type=int, default=90, help='Target console width for epoch summary lines (wrap if exceeded).')
    parser.add_argument('--no_color', action='store_true', help='Disable ANSI colors in console output.')
    parser.add_argument('--debug', action='store_true', help='After each epoch, save and immediately reload the checkpoint to verify persistence.')

    # Evaluation controls
    parser.add_argument('--loss_audit', action='store_true',
                        help='During eval (eval-only or on-start), compute and print a detailed loss/metric audit breakdown.')
    parser.add_argument('--deterministic_eval', action='store_true',
                        help='Force deterministic settings during evaluation (set seeds, deterministic algorithms, disable AMP).')
    parser.add_argument('--seed', type=int, default=12345, help='Random seed to use when --deterministic_eval is set.')
    parser.add_argument('--enforce_resume_sanity', action='store_true',
                        help='Shortcut: implies --eval_on_start --fail_if_worse with current tolerances.')

    # Evaluation controls
    parser.add_argument('--eval_on_start', action='store_true',
                        help='If set, run a full validation evaluation immediately after loading a checkpoint.')
    parser.add_argument('--eval_only', type=str, default=None,
                        help='If provided, load this checkpoint, run full validation once, print results, and exit (no training).')
    parser.add_argument('--eval_tol_rmse', type=float, default=1e-3,
                        help='Tolerance for RMSE difference vs. embedded checkpoint metrics to consider "close".')
    parser.add_argument('--eval_tol_loss', type=float, default=0.01,
                        help='Relative tolerance for loss difference (e.g., 0.01 = 1%) vs. embedded checkpoint metrics.')
    parser.add_argument('--fail_if_worse', action='store_true',
                        help='When evaluating on start or eval-only, exit with non-zero code if metrics regress beyond tolerances.')

    # DataLoader performance controls (be careful with num_workers on Windows)
    parser.add_argument('--num_workers', type=int, default=0,
                        help='DataLoader workers. WARNING: On Windows with a large in-memory TensorDataset,\n'
                             'setting this >0 can duplicate the dataset in each worker and blow up RAM. Use with care.')
    parser.add_argument('--prefetch_factor', type=int, default=2,
                        help='Number of batches prefetched per worker when num_workers>0.')
    parser.add_argument('--persistent_workers', action='store_true',
                        help='Keep DataLoader workers alive between epochs (requires num_workers>0).')
    parser.add_argument('--no_pin_memory', action='store_true',
                        help='Disable pinned memory for host-to-device copies.')

    # Perf/instrumentation
    parser.add_argument('--profile_steps', type=int, default=0,
                        help='If >0, log per-step detailed timings for the first N steps of each epoch.')
    parser.add_argument('--sync_profile', action='store_true',
                        help='Force CUDA synchronize around profiled regions for accurate timings (slower).')
    parser.add_argument('--amp', action='store_true',
                        help='Enable torch.cuda.amp mixed precision for faster training on NVIDIA GPUs.')
    parser.add_argument('--compile', action='store_true',
                        help='Enable torch.compile to fuse/optimize model for PyTorch 2.x (may require warmup).')

    # Fast debug / limits
    parser.add_argument('--fast_debug', action='store_true', help='Use tiny settings for quick runs')
    parser.add_argument('--train_limit', type=int, default=None, help='Cap number of training rows (subset).')
    parser.add_argument('--val_limit', type=int, default=None, help='Cap number of validation rows (subset).')

    # Checkpointing / logging
    parser.add_argument('--resume_checkpoint', type=str, default=None,
                        help='Path to a checkpoint .pt file to resume from.')
    parser.add_argument('--no_wandb', action='store_true', help='Disable Weights & Biases logging')

    # Step logging verbosity
    parser.add_argument('--log_steps', action='store_true', help='Log per-step losses to TensorBoard (and W&B).')

    args = parser.parse_args()

    # Convenience: enforce resume sanity
    if getattr(args, 'enforce_resume_sanity', False):
        setattr(args, 'eval_on_start', True)
        setattr(args, 'fail_if_worse', True)

    # Preferences and roots
    prefs = _load_preferences(args.preferences)
    root_dir = args.root or getattr(prefs, 'root_path', os.getcwd())

    # Resolve file paths
    train_path = os.path.join(root_dir, args.train_file)
    val_path = os.path.join(root_dir, args.val_file)
    test_path = os.path.join(root_dir, args.test_file) if getattr(args, 'test_file', None) else None

    if not os.path.isfile(train_path):
        raise FileNotFoundError(f"Training cached file not found: {train_path}")
    if not os.path.isfile(val_path):
        raise FileNotFoundError(f"Validation cached file not found: {val_path}")
    if test_path is not None and not os.path.isfile(test_path):
        logger.warning(f"Test cached file specified but not found: {test_path}. Skipping test evaluation.")
        test_path = None

    # Effective settings
    batch_size = int(args.batch_size)
    num_epochs = int(args.epochs)
    lr = float(args.learning_rate)
    save_every = max(1, int(args.save_interval))

    if args.fast_debug:
        # Keep memory/time small for quick iteration
        num_epochs = min(1, num_epochs)
        batch_size = min(128, batch_size)
        if args.train_limit is None:
            args.train_limit = 10_000
        if args.val_limit is None:
            args.val_limit = 10_000
        logger.info("FAST DEBUG active: epochs=%s, batch_size=%s, train_limit=%s, val_limit=%s",
                    num_epochs, batch_size, args.train_limit, args.val_limit)

    # -------- wandb: run init & notes --------
    wandb_run = None
    if not args.no_wandb:
        # Try to include the model source code as 'notes' to the run for convenience
        notes_content = ""
        model_filepath = os.path.join(PARENT_DIR, 'encoder', 'model_WAE_01.py')
        try:
            with open(model_filepath, 'r') as f:
                notes_content = f.read()
        except Exception as e:
            notes_content = f"Failed to load model file: {e}"

        # On Windows, disable symlinks to avoid WinError 1314 during wandb.save
        try:
            import platform
            is_windows = platform.system().lower().startswith('win')
        except Exception:
            is_windows = False

        wandb_run = wandb.init(
            project=MODEL_NAME,
            name=f"{MODEL_NAME}_run",
            notes=notes_content,
            config={
                'model': MODEL_NAME,
                'batch_size': batch_size,
                'epochs': num_epochs,
                'learning_rate': lr,
                'train_path': train_path,
                'val_path': val_path,
            },
            settings=wandb.Settings(symlink=not is_windows)
        )

    # Device setup & diagnostic
    device, acc_info = accelerator_report()
    try:
        if not args.no_wandb:
            wandb.config.update({'accelerator': acc_info}, allow_val_change=True)
    except Exception:
        pass

    # Output directories (relative to this script working directory)
    save_dir = os.path.join(PARENT_DIR, 'encoder', 'saved_models')
    log_dir = os.path.join(PARENT_DIR, 'encoder', 'logs')
    os.makedirs(save_dir, exist_ok=True)
    os.makedirs(log_dir, exist_ok=True)

    # TensorBoard writer
    writer = SummaryWriter(log_dir=log_dir)

    # ------------------
    # Data: load & wrap
    # ------------------
    train_np = _load_cached_array(train_path, limit=args.train_limit)
    val_np = _load_cached_array(val_path, limit=args.val_limit)

    train_loader = _make_loader(
        train_np,
        batch_size=batch_size,
        shuffle=True,
        num_workers=int(args.num_workers),
        prefetch_factor=int(args.prefetch_factor),
        persistent_workers=bool(args.persistent_workers),
        pin_memory=not args.no_pin_memory,
    )
    val_loader = _make_loader(
        val_np,
        batch_size=batch_size,
        shuffle=False,
        num_workers=int(args.num_workers),
        prefetch_factor=int(args.prefetch_factor),
        persistent_workers=bool(args.persistent_workers),
        pin_memory=not args.no_pin_memory,
    )

    # Free NumPy arrays early to reduce memory pressure; data now lives in tensors.
    del train_np
    del val_np

    # ---------------
    # Model & optim
    # ---------------
    model = WAE().to(device)

    # Optional compile for PyTorch 2.x
    if getattr(args, 'compile', False):
        try:
            model = torch.compile(model, mode='max-autotune')
            logger.info("Enabled torch.compile(max-autotune) for model")
        except Exception as e:
            logger.warning(f"torch.compile requested but failed: {e}")

    try:
        if device.type == 'cuda':
            torch.backends.cudnn.benchmark = True
    except Exception:
        pass
    # Prefer TensorFloat-32 / high-precision matmul for speed on Ampere+ GPUs when appropriate
    try:
        if device.type == 'cuda':
            torch.set_float32_matmul_precision('high')  # allowed: highest, high, medium
    except Exception:
        pass

    optimizer = optim.Adam(model.parameters(), lr=lr)

    # AMP mixed precision support
    use_amp = bool(args.amp and device.type == 'cuda')
    try:
        from torch.cuda.amp import GradScaler, autocast
    except Exception:
        GradScaler = None
        autocast = None
        use_amp = False
    scaler = GradScaler(enabled=use_amp) if GradScaler is not None else None

    start_epoch = 0

    # Optional: resume from checkpoint or eval-only
    resume_path = args.resume_checkpoint
    # eval-only override
    if getattr(args, 'eval_only', None):
        resume_path = args.eval_only
    if resume_path is None:
        # Convenience default: try the model's final checkpoint name in save_dir
        default_final = os.path.join(save_dir, f"{MODEL_NAME}_final.pt")
        if os.path.isfile(default_final):
            resume_path = default_final
    if resume_path and os.path.isfile(resume_path):
        try:
            logger.info(f"Loading checkpoint from {resume_path}")
            try:
                checkpoint = torch.load(resume_path, map_location=device, weights_only=False)
            except TypeError:
                # Older PyTorch versions do not support weights_only; fallback to legacy behavior
                checkpoint = torch.load(resume_path, map_location=device)
            model.load_state_dict(checkpoint['model_state_dict'])
            if 'optimizer_state_dict' in checkpoint:
                optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
                # Move optimizer state to device
                for state in optimizer.state.values():
                    for k, v in state.items():
                        if isinstance(v, torch.Tensor):
                            state[k] = v.to(device)
            if 'scaler_state_dict' in checkpoint and scaler is not None:
                scaler.load_state_dict(checkpoint['scaler_state_dict'])
            # Adopt start_epoch from checkpoint if present (first next epoch will be start_epoch+1)
            try:
                start_epoch = int(checkpoint.get('epoch', start_epoch))
            except Exception:
                pass
            # If metrics are embedded, print them for context
            ckpt_metrics = checkpoint.get('metrics')
            if isinstance(ckpt_metrics, dict):
                try:
                    msg = (
                        f"RESUME METRICS epoch={ckpt_metrics.get('epoch')} "
                        f"train_loss={_fmt_val(ckpt_metrics.get('train_loss', float('nan')))} "
                        f"val_loss={_fmt_val(ckpt_metrics.get('val_loss', float('nan')))} "
                        f"train_RMSE={_fmt_val(ckpt_metrics.get('train_RMSE')) if ckpt_metrics.get('train_RMSE') is not None else 'N/A'} "
                        f"val_RMSE={_fmt_val(ckpt_metrics.get('val_RMSE', float('nan')))}"
                    )
                    logger.info(msg)
                except Exception:
                    pass
            # If provenance is embedded, print a concise summary
            ckpt_prov = checkpoint.get('provenance')
            if isinstance(ckpt_prov, dict):
                try:
                    # Recompute live checksums for comparison
                    s_now, a_now = _model_checksum(model)
                    os_now_s, os_now_a = _optimizer_checksum(optimizer)
                    cs = ckpt_prov.get('model_checksum', {})
                    cos = ckpt_prov.get('optimizer_checksum', {})
                    rc = ckpt_prov.get('run_config', {})
                    data = ckpt_prov.get('data', {})
                    logger.info("PROVENANCE: model_name=%s device=%s params=%s",
                                ckpt_prov.get('model_name'), ckpt_prov.get('device'), ckpt_prov.get('param_count'))
                    logger.info("PROVENANCE: python=%s torch=%s cuda=%s host=%s",
                                ckpt_prov.get('python'), ckpt_prov.get('torch'), ckpt_prov.get('cuda_version'), ckpt_prov.get('host'))
                    logger.info("PROVENANCE: train_path=%s size=%s mtime=%s | val_path=%s size=%s mtime=%s",
                                data.get('train_path'),
                                (data.get('train_file') or {}).get('size'),
                                (data.get('train_file') or {}).get('mtime'),
                                data.get('val_path'),
                                (data.get('val_file') or {}).get('size'),
                                (data.get('val_file') or {}).get('mtime'))
                    logger.info("PROVENANCE: config batch_size=%s lr=%s amp=%s workers=%s limits(train=%s,val=%s)",
                                rc.get('batch_size'), rc.get('learning_rate'), rc.get('amp'), rc.get('num_workers'), rc.get('train_limit'), rc.get('val_limit'))
                    # New: dataset and model source hashes
                    try:
                        tf = (data.get('train_file') or {})
                        vf = (data.get('val_file') or {})
                        ms = ckpt_prov.get('model_source') or {}
                        logger.info("PROVENANCE: train_sha256=%s | val_sha256=%s | model_src_sha256=%s",
                                    tf.get('sha256'), vf.get('sha256'), (ms.get('sha256') if isinstance(ms, dict) else None))
                        if ms:
                            logger.info("PROVENANCE: model_source path=%s size=%s mtime=%s",
                                        ms.get('path'), ms.get('size'), ms.get('mtime'))
                    except Exception:
                        pass
                    logger.info("PROVENANCE: model_checksum(sum=%.6e,abs=%.6e) match=%s | now(sum=%.6e,abs=%.6e)",
                                float(cs.get('sum', float('nan'))), float(cs.get('abs_sum', float('nan'))),
                                (abs(float(cs.get('sum', 0.0)) - s_now) < 1e-6 and abs(float(cs.get('abs_sum', 0.0)) - a_now) < 1e-6),
                                s_now, a_now)
                    logger.info("PROVENANCE: optim_checksum(sum=%.6e,abs=%.6e) match=%s | now(sum=%.6e,abs=%.6e)",
                                float(cos.get('sum', float('nan'))), float(cos.get('abs_sum', float('nan'))),
                                (abs(float(cos.get('sum', 0.0)) - os_now_s) < 1e-6 and abs(float(cos.get('abs_sum', 0.0)) - os_now_a) < 1e-6),
                                os_now_s, os_now_a)
                except Exception as e:
                    logger.warning(f"Failed to print provenance summary: {e}")
        except Exception as e:
            logger.error(f"Failed to load checkpoint: {e}")
            logger.error("Training will start from scratch.")
            
        # Evaluation on start (full validation) if requested or if resuming
        try:
            eval_on_start_flag = bool(getattr(args, 'eval_on_start', False)) or bool(resume_path)
        except Exception:
            eval_on_start_flag = bool(resume_path)
        if eval_on_start_flag:
            # Deterministic evaluation if requested
            if getattr(args, 'deterministic_eval', False):
                _set_deterministic(int(getattr(args, 'seed', 12345)))
            eval_res = _evaluate_full(model, val_loader, device, audit=bool(getattr(args, 'loss_audit', False)))
            ckpt_metrics = checkpoint.get('metrics') if 'checkpoint' in locals() else None
            msg = (
                f"EVAL-ON-START: val_loss={_fmt_val(eval_res['loss'])} val_recon={_fmt_val(eval_res['recon'])} "
                f"val_mmd={_fmt_val(eval_res['mmd'])} val_triplet={_fmt_val(eval_res['triplet'])} "
                f"val_RMSE={_fmt_val(eval_res['rmse'])} batches={eval_res['batches']}"
            )
            logger.info(msg)
            if getattr(args, 'loss_audit', False) and isinstance(eval_res.get('audit'), dict):
                a = eval_res['audit']
                logger.info(
                    "LOSS-AUDIT: instances=%s elements=%s mean_recon_logcosh_per_instance=%s max_recon_logcosh_over_set=%s "
                    "mean_triplet63_mse_per_instance=%s rmse=%s mse=%s",
                    a.get('instances'), a.get('elements'), _fmt_val(a.get('mean_recon_logcosh_per_instance')),
                    _fmt_val(a.get('max_recon_logcosh_over_set') if a.get('max_recon_logcosh_over_set') is not None else float('nan')),
                    _fmt_val(a.get('mean_triplet63_mse_per_instance')),
                    _fmt_val(a.get('rmse')), _fmt_val(a.get('mse'))
                )
            # If checkpoint has embedded metrics, print diffs and optionally enforce tolerances
            if isinstance(ckpt_metrics, dict):
                def rel_diff(curr, ref):
                    try:
                        return abs((curr - ref) / max(1e-12, abs(ref)))
                    except Exception:
                        return float('inf')
                diffs = {
                    'rmse_abs': (abs(eval_res['rmse'] - float(ckpt_metrics.get('val_RMSE', float('nan'))))
                                 if ckpt_metrics.get('val_RMSE') is not None else float('nan')),
                    'loss_rel': rel_diff(eval_res['loss'], float(ckpt_metrics.get('val_loss', float('nan'))))
                }
                logger.info(
                    "EVAL-ON-START Δ vs ckpt: ΔRMSE=%.6f (abs), Δloss=%.4f (rel)",
                    diffs['rmse_abs'], diffs['loss_rel']
                )
                # W&B log
                if not args.no_wandb:
                    try:
                        wandb.log({
                            'eval_on_start/val_loss': eval_res['loss'],
                            'eval_on_start/val_recon': eval_res['recon'],
                            'eval_on_start/val_mmd': eval_res['mmd'],
                            'eval_on_start/val_triplet': eval_res['triplet'],
                            'eval_on_start/val_RMSE': eval_res['rmse'],
                            'eval_on_start/delta_rmse_abs': diffs['rmse_abs'],
                            'eval_on_start/delta_loss_rel': diffs['loss_rel'],
                        })
                    except Exception:
                        pass
                # Enforce tolerances if requested
                if getattr(args, 'fail_if_worse', False):
                    tol_rmse = float(getattr(args, 'eval_tol_rmse', 1e-3))
                    tol_loss = float(getattr(args, 'eval_tol_loss', 0.01))
                    if (diffs['rmse_abs'] > tol_rmse) or (diffs['loss_rel'] > tol_loss):
                        logger.error(
                            "EVAL-ON-START failed tolerances (ΔRMSE>%.3g or Δloss>%.3g). Exiting.",
                            tol_rmse, tol_loss
                        )
                        try:
                            import sys as _sys
                            _sys.exit(2)
                        except SystemExit:
                            return
            # If eval-only was requested, exit after evaluation
            if getattr(args, 'eval_only', None):
                try:
                    import sys as _sys
                    _sys.exit(0)
                except SystemExit:
                    return
        # back to train mode
        model.train()

    logger.info(f"Initialized WAE model with latent dimension {model.fc4.out_features}")

    # =================
    # Training routine
    # =================
    global_step = 0
    train_start = time.time()
    prev_metrics = {}

    for epoch in range(start_epoch, num_epochs):
        model.train()
        epoch_loss = 0.0
        epoch_recon = 0.0
        epoch_mmd = 0.0
        epoch_triplet = 0.0
        num_batches = 0
        epoch_t0 = time.time()
        # Train SSE/MSE accumulators
        train_sse_sum = 0.0
        train_elem_sum = 0

        # Profiling controls
        profile_n = int(getattr(args, 'profile_steps', 0) or 0)
        sync_profile = bool(getattr(args, 'sync_profile', False)) and (device.type == 'cuda')
        step_idx = 0

        for batch in train_loader:
            step_wall_t0 = time.time()
            # batch is a tuple from TensorDataset
            x_cpu = batch[0]

            # Move to device; `pin_memory=True` at loader level enables non_blocking
            t_h2d0 = time.time()
            x = x_cpu.to(device, non_blocking=(device.type == 'cuda'))
            if sync_profile:
                torch.cuda.synchronize()
            t_h2d1 = time.time()

            # Forward
            t_fwd0 = time.time()
            if use_amp:
                with autocast():
                    recon_x, z = model(x)
                    loss, recon_loss, mmd_loss, triplet_loss = model.loss_function(recon_x, x, z)
            else:
                recon_x, z = model(x)
                loss, recon_loss, mmd_loss, triplet_loss = model.loss_function(recon_x, x, z)
            if sync_profile:
                torch.cuda.synchronize()
            t_fwd1 = time.time()

            # Backward + step
            t_bwd0 = time.time()
            optimizer.zero_grad(set_to_none=True)
            if use_amp and scaler is not None:
                scaler.scale(loss).backward()
                if sync_profile:
                    torch.cuda.synchronize()
                t_bwd1 = time.time()
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                if sync_profile:
                    torch.cuda.synchronize()
                t_bwd1 = time.time()
                optimizer.step()
            if sync_profile:
                torch.cuda.synchronize()
            t_step1 = time.time()

            # Metrics
            l = float(loss.item())
            r = float(recon_loss.item())
            m = float(mmd_loss.item())
            t = float(triplet_loss.item())
            epoch_loss += l
            epoch_recon += r
            epoch_mmd += m
            epoch_triplet += t
            # Train SSE/MSE accum
            try:
                sse_batch = torch.sum((recon_x - x) ** 2).item()
                train_sse_sum += float(sse_batch)
                train_elem_sum += int(x.numel())
            except Exception:
                pass
            num_batches += 1
            global_step += 1

            # Optional per-step profiling for first N steps
            if profile_n > 0 and step_idx < profile_n:
                bs = int(x.size(0))
                # Times
                dt_h2d = max(1e-9, t_h2d1 - t_h2d0)
                dt_fwd = max(1e-9, t_fwd1 - t_fwd0)
                dt_bwd = max(1e-9, t_bwd1 - t_bwd0)
                dt_wall = max(1e-9, t_step1 - step_wall_t0)
                # Throughputs
                samples_per_s = bs / dt_wall
                mb_h2d = (x.numel() * x.element_size()) / 1e6
                h2d_gbps = (mb_h2d / dt_h2d) / 1024.0  # GB/s
                # CUDA memory stats (if CUDA)
                mem_alloc_mb = mem_max_mb = None
                if device.type == 'cuda':
                    try:
                        mem_alloc_mb = torch.cuda.memory_allocated() / (1024**2)
                        mem_max_mb = torch.cuda.max_memory_allocated() / (1024**2)
                    except Exception:
                        pass
                logger.info(
                    f"[Profile] epoch={epoch+1} step={step_idx+1} bs={bs} "
                    f"h2d={dt_h2d*1000:.2f}ms fwd={dt_fwd*1000:.2f}ms bwd={dt_bwd*1000:.2f}ms "
                    f"wall={dt_wall*1000:.2f}ms thr={samples_per_s:.1f} samples/s "
                    f"H2D~{h2d_gbps:.2f} GB/s mem={mem_alloc_mb:.0f}/{mem_max_mb:.0f} MiB"
                )
                # Log to W&B as well
                if not args.no_wandb:
                    wandb.log({
                        'profile/h2d_ms': dt_h2d * 1000.0,
                        'profile/fwd_ms': dt_fwd * 1000.0,
                        'profile/bwd_ms': dt_bwd * 1000.0,
                        'profile/wall_ms': dt_wall * 1000.0,
                        'profile/samples_per_s': samples_per_s,
                        'profile/h2d_GBps': h2d_gbps,
                        'profile/mem_alloc_MiB': mem_alloc_mb,
                        'profile/mem_max_MiB': mem_max_mb,
                        'global_step': global_step,
                        'epoch': epoch,
                    })
                step_idx += 1

            if args.log_steps:
                writer.add_scalar('Loss/train_step', l, global_step)
                writer.add_scalar('Loss/recon_step', r, global_step)
                writer.add_scalar('Loss/mmd_step', m, global_step)
                writer.add_scalar('Loss/triplet_step', t, global_step)
                if not args.no_wandb:
                    wandb.log({
                        'Loss/train_step': l,
                        'Loss/recon_step': r,
                        'Loss/mmd_step': m,
                        'Loss/triplet_step': t,
                        'global_step': global_step,
                    })

        # Epoch aggregates
        avg_loss = epoch_loss / max(1, num_batches)
        avg_recon = epoch_recon / max(1, num_batches)
        avg_mmd = epoch_mmd / max(1, num_batches)
        avg_triplet = epoch_triplet / max(1, num_batches)
        epoch_time = time.time() - epoch_t0

        # Validation
        model.eval()
        val_loss_sum = 0.0
        val_recon_sum = 0.0
        val_mmd_sum = 0.0
        val_triplet_sum = 0.0
        val_batches = 0
        val_l2_sum = 0.0  # RMSE accumulated per-batch
        # Val SSE/MSE accumulators
        val_sse_sum = 0.0
        val_elem_sum = 0
        with torch.no_grad():
            for batch in val_loader:
                x_cpu = batch[0]
                x = x_cpu.to(device, non_blocking=(device.type == 'cuda'))
                recon_x, z = model(x)
                loss, recon_loss, mmd_loss, triplet_loss = model.loss_function(recon_x, x, z)
                val_loss_sum += float(loss.item())
                val_recon_sum += float(recon_loss.item())
                val_mmd_sum += float(mmd_loss.item())
                val_triplet_sum += float(triplet_loss.item())
                # Calculate L2 error (RMSE per value)
                l2_error = torch.sqrt(torch.mean((recon_x - x) ** 2))
                val_l2_sum += float(l2_error.item())
                # SSE/MSE accumulators for exact RMSE over all elements
                try:
                    sse_batch = torch.sum((recon_x - x) ** 2).item()
                    val_sse_sum += float(sse_batch)
                    val_elem_sum += int(x.numel())
                except Exception:
                    pass
                val_batches += 1

        # ---- Aggregate validation metrics ----
        val_avg_loss = val_loss_sum / max(1, val_batches)
        val_avg_recon = val_recon_sum / max(1, val_batches)
        val_avg_mmd = val_mmd_sum / max(1, val_batches)
        val_avg_triplet = val_triplet_sum / max(1, val_batches)
        # Global RMSE over all elements (preferred); fallback to mean of per-batch RMSE
        train_rmse = (float(np.sqrt(train_sse_sum / train_elem_sum)) if train_elem_sum > 0 else None)
        val_rmse = (float(np.sqrt(val_sse_sum / val_elem_sum)) if val_elem_sum > 0 else (val_l2_sum / max(1, val_batches)))

        # ---- Epoch summary & logging ----
        elapsed = epoch_time
        remaining_epochs = (num_epochs - (epoch + 1))
        eta_total_sec = elapsed * remaining_epochs
        eta_min = int(eta_total_sec // 60)
        eta_sec = int(eta_total_sec % 60)

        # Build width-aware, non-rainbow summary with subtle colored deltas
        width = int(getattr(args, 'width', 90) or 90)
        color_enabled = not bool(getattr(args, 'no_color', False))

        parts_train = [
            f"Epoch {epoch+1}/{num_epochs}:",
            f"train_loss={_fmt_val(avg_loss)}{_fmt_delta(avg_loss, prev_metrics.get('train_loss'), decimals=3, color_enabled=color_enabled)}",
            f"recon={_fmt_val(avg_recon)}{_fmt_delta(avg_recon, prev_metrics.get('train_recon'), decimals=3, color_enabled=color_enabled)}",
            f"mmd={_fmt_val(avg_mmd)}{_fmt_delta(avg_mmd, prev_metrics.get('train_mmd'), decimals=3, color_enabled=color_enabled)}",
            f"triplet={_fmt_val(avg_triplet)}{_fmt_delta(avg_triplet, prev_metrics.get('train_triplet'), decimals=3, color_enabled=color_enabled)}",
        ]
        parts_val = [
            f"val_loss={_fmt_val(val_avg_loss)}{_fmt_delta(val_avg_loss, prev_metrics.get('val_loss'), decimals=3, color_enabled=color_enabled)}",
            f"val_recon={_fmt_val(val_avg_recon)}{_fmt_delta(val_avg_recon, prev_metrics.get('val_recon'), decimals=3, color_enabled=color_enabled)}",
            f"val_mmd={_fmt_val(val_avg_mmd)}{_fmt_delta(val_avg_mmd, prev_metrics.get('val_mmd'), decimals=3, color_enabled=color_enabled)}",
            f"val_triplet={_fmt_val(val_avg_triplet)}{_fmt_delta(val_avg_triplet, prev_metrics.get('val_triplet'), decimals=3, color_enabled=color_enabled)}",
        ]
        parts_rmse = []
        if train_rmse is not None:
            parts_rmse.append(f"train_RMSE={_fmt_val(train_rmse)}{_fmt_delta(train_rmse, prev_metrics.get('train_RMSE'), decimals=3, color_enabled=color_enabled)}")
        parts_rmse.append(f"val_RMSE={_fmt_val(val_rmse)}{_fmt_delta(val_rmse, prev_metrics.get('val_RMSE'), decimals=3, color_enabled=color_enabled)}")
        tail = f"epoch_time={elapsed:.1f}s | ETA~{eta_min}m{eta_sec:02d}s"

        # Assemble with wrapping at separators ' | '
        def assemble(linesets):
            out_lines = []
            line = ''
            for idx, parts in enumerate(linesets):
                for p in parts:
                    sep = ' ' if (line == '' or line.endswith(':')) else ' '
                    candidate = (line + sep + p) if line else p
                    if len(candidate) > width and line:
                        out_lines.append(line)
                        line = p
                    else:
                        line = candidate
                # add separator between sections
                section_sep = ' | '
                candidate = line + section_sep
                if len(candidate) > width and line:
                    out_lines.append(line)
                    line = ''
                else:
                    line = candidate
            # append tail intelligently
            tail_candidate = (line + tail) if line else tail
            if len(tail_candidate) > width and line:
                out_lines.append(line.rstrip(' | '))
                out_lines.append(tail)
            else:
                out_lines.append(tail_candidate.rstrip())
            return '\n'.join(out_lines)

        msg = assemble([parts_train, parts_val, parts_rmse])

        # Log once (avoid duplicate console output)
        logger.info("\n" + msg if "\n" in msg else msg)

        # TensorBoard scalars
        writer.add_scalar('epoch/train_loss', avg_loss, epoch+1)
        writer.add_scalar('epoch/train_recon', avg_recon, epoch+1)
        writer.add_scalar('epoch/train_mmd', avg_mmd, epoch+1)
        writer.add_scalar('epoch/train_triplet', avg_triplet, epoch+1)
        writer.add_scalar('epoch/val_loss', val_avg_loss, epoch+1)
        writer.add_scalar('epoch/val_recon', val_avg_recon, epoch+1)
        writer.add_scalar('epoch/val_mmd', val_avg_mmd, epoch+1)
        writer.add_scalar('epoch/val_triplet', val_avg_triplet, epoch+1)
        if train_rmse is not None:
            writer.add_scalar('epoch/train_RMSE', train_rmse, epoch+1)
        writer.add_scalar('epoch/val_RMSE', val_rmse, epoch+1)

        # W&B logging
        if not args.no_wandb:
            try:
                wandb.log({
                    'epoch': epoch + 1,
                    'global_step': global_step,
                    'epoch/train_loss': avg_loss,
                    'epoch/train_recon': avg_recon,
                    'epoch/train_mmd': avg_mmd,
                    'epoch/train_triplet': avg_triplet,
                    'epoch/val_loss': val_avg_loss,
                    'epoch/val_recon': val_avg_recon,
                    'epoch/val_mmd': val_avg_mmd,
                    'epoch/val_triplet': val_avg_triplet,
                    **({'epoch/train_RMSE': train_rmse} if train_rmse is not None else {}),
                    'epoch/val_RMSE': val_rmse,
                    'epoch/seconds': elapsed,
                })
            except Exception as e:
                logger.warning(f"wandb.log failed: {e}")

        # Update previous metrics for delta coloring
        prev_metrics = {
            'train_loss': avg_loss,
            'train_recon': avg_recon,
            'train_mmd': avg_mmd,
            'train_triplet': avg_triplet,
            'val_loss': val_avg_loss,
            'val_recon': val_avg_recon,
            'val_mmd': val_avg_mmd,
            'val_triplet': val_avg_triplet,
            'train_RMSE': train_rmse if train_rmse is not None else prev_metrics.get('train_RMSE'),
            'val_RMSE': val_rmse,
        }

        # ---- Checkpointing ----
        do_save = ((epoch + 1) % save_every == 0)
        if do_save:
            ckpt_path = os.path.join(save_dir, f"{MODEL_NAME}_epoch_{epoch+1}.pt")
            try:
                ckpt_metrics = {
                    'epoch': epoch + 1,
                    'train_loss': float(avg_loss),
                    'train_recon': float(avg_recon),
                    'train_mmd': float(avg_mmd),
                    'train_triplet': float(avg_triplet),
                    'val_loss': float(val_avg_loss),
                    'val_recon': float(val_avg_recon),
                    'val_mmd': float(val_avg_mmd),
                    'val_triplet': float(val_avg_triplet),
                    'train_RMSE': (float(train_rmse) if train_rmse is not None else None),
                    'val_RMSE': float(val_rmse),
                    'epoch_time_s': float(elapsed),
                    'global_step': int(global_step),
                }
                ckpt_prov = _build_provenance(
                    model, optimizer, acc_info, args,
                    model_name=MODEL_NAME,
                    train_path=train_path,
                    val_path=val_path,
                    num_epochs=num_epochs,
                    batch_size=batch_size,
                    lr=lr,
                    save_every=save_every,
                )
                torch.save({
                    'model_state_dict': model.state_dict(),
                    'optimizer_state_dict': optimizer.state_dict(),
                    'scaler_state_dict': (scaler.state_dict() if (scaler is not None and use_amp) else None),
                    'epoch': epoch + 1,
                    'global_step': global_step,
                    'model_name': MODEL_NAME,
                    'accelerator': acc_info,
                    'metrics': ckpt_metrics,
                    'provenance': ckpt_prov,
                }, ckpt_path)
                logger.info(f"Saved checkpoint: {ckpt_path}")
            except Exception as e:
                logger.warning(f"Failed to save checkpoint {ckpt_path}: {e}")

            # Prune older checkpoints in project dir
            try:
                prune_checkpoints(save_dir, MODEL_NAME, CHECKPOINTS_TO_KEEP)
            except Exception as e:
                logger.warning(f"prune_checkpoints failed: {e}")

            # Also copy into W&B run directory on Windows (symlink disabled)
            try:
                if not args.no_wandb and wandb_run is not None:
                    run_dir = getattr(wandb_run, 'dir', None)
                    if run_dir:
                        dst_dir = os.path.join(run_dir, 'files', 'saved_models')
                        os.makedirs(dst_dir, exist_ok=True)
                        shutil.copy2(ckpt_path, dst_dir)
                        logger.info(f"Copied checkpoint into W&B run dir: {dst_dir}")
                        prune_wandb_checkpoints_if_present(MODEL_NAME, CHECKPOINTS_TO_KEEP)
            except Exception as e:
                logger.warning(f"Failed to copy/prune W&B checkpoint: {e}")

        # -- Debug: verify save/load persistence each epoch --
        if getattr(args, 'debug', False):
            tmp_ckpt = os.path.join(save_dir, f"__debug_tmp_{MODEL_NAME}.pt")
            try:
                torch.save({
                    'model_state_dict': model.state_dict(),
                    'optimizer_state_dict': optimizer.state_dict(),
                    'scaler_state_dict': (scaler.state_dict() if (scaler is not None and use_amp) else None),
                }, tmp_ckpt)
                # Load back into a fresh model and compare checksums
                fresh_model = WAE().to(device)
                try:
                    loaded = torch.load(tmp_ckpt, map_location=device, weights_only=False)
                except TypeError:
                    loaded = torch.load(tmp_ckpt, map_location=device)
                fresh_model.load_state_dict(loaded['model_state_dict'])
                s_live, a_live = _model_checksum(model)
                s_load, a_load = _model_checksum(fresh_model)
                ds = abs(s_live - s_load)
                da = abs(a_live - a_load)
                ok = (ds <= 1e-5 * max(1.0, abs(s_live))) and (da <= 1e-5 * max(1.0, abs(a_live)))
                logger.info(f"DEBUG PERSISTENCE: model checksum match={ok} ds={ds:.6e} da={da:.6e}")
            except Exception as e:
                logger.warning(f"DEBUG PERSISTENCE failed: {e}")
            finally:
                try:
                    if os.path.exists(tmp_ckpt):
                        os.remove(tmp_ckpt)
                except Exception:
                    pass

        # end for epoch

    # Optional: evaluate on test set if provided
    if 'test_path' in locals() and test_path is not None:
        try:
            test_np = _load_cached_array(test_path, limit=None)
            test_loader = _make_loader(
                test_np,
                batch_size=batch_size,
                shuffle=False,
                num_workers=int(args.num_workers),
                prefetch_factor=int(args.prefetch_factor),
                persistent_workers=bool(args.persistent_workers),
                pin_memory=not args.no_pin_memory,
            )
            del test_np
            test_res = _evaluate_full(model, test_loader, device)
            logger.info(
                "TEST EVAL: loss=%s recon=%s mmd=%s triplet=%s RMSE=%s batches=%s",
                _fmt_val(test_res['loss']), _fmt_val(test_res['recon']), _fmt_val(test_res['mmd']),
                _fmt_val(test_res['triplet']), _fmt_val(test_res['rmse']), test_res['batches']
            )
            # TensorBoard
            writer.add_scalar('test/loss', test_res['loss'], num_epochs)
            writer.add_scalar('test/recon', test_res['recon'], num_epochs)
            writer.add_scalar('test/mmd', test_res['mmd'], num_epochs)
            writer.add_scalar('test/triplet', test_res['triplet'], num_epochs)
            writer.add_scalar('test/RMSE', test_res['rmse'], num_epochs)
            # W&B
            if not args.no_wandb:
                try:
                    wandb.log({
                        'test/loss': test_res['loss'],
                        'test/recon': test_res['recon'],
                        'test/mmd': test_res['mmd'],
                        'test/triplet': test_res['triplet'],
                        'test/RMSE': test_res['rmse'],
                        'test/batches': test_res['batches'],
                        'epoch': num_epochs,
                        'global_step': global_step,
                    })
                except Exception:
                    pass
        except Exception as e:
            logger.warning(f"Test evaluation failed: {e}")

    # Close writers
    try:
        writer.flush()
        writer.close()
    except Exception:
        pass

    # Finish W&B run if active
    try:
        if not args.no_wandb and wandb_run is not None:
            wandb.finish()
    except Exception:
        pass

if __name__ == "__main__":
    # Entry point to start training when this script is executed directly
    main()
